### ISSUE TITLE
Is the ANCOMBC currently available?

### ISSUE THREAD

**Issue by GeoffZheDu** [FrederickHuangLin/ANCOMBC#1]
Hi, Huang,

I am wondering if the ANCOMBC is currently available? I am really interested in trying it. I tried to install either the latest released or development version using code listed in the install section, but none of them worked for me.

Thanks!

Best regards,
Zhe

**Comment by FrederickHuangLin** [comment]
Hi Zhe,

Thanks for your interest in ANCOMBC. 

ANCOMBC is currently under review with Bioconductor and has not yet officially released. It usually takes 2 - 5 weeks to process.

Stay tuned!

Best,

Huang

**Comment by rusher321** [comment]
Hi, Huang,

The review in Bioconductor finished? 
I tried to install ANCOMBC for Github or Bioconductor, but it doesn't work. 
When using Github to install. I got the error:

> > library("devtools")
> > install_github("Bioconductor-mirror/ANCOMBC")
> Error: Failed to install 'unknown package' from GitHub:
>   HTTP error 404.
>   Not Found
> 
>   Did you spell the repo owner (`Bioconductor-mirror`) and repo name (`ANCOMBC`) correctly?
>   - If spelling is correct, check that you have the required permissions to access the repo.



Thanks!

Best regards,
Huahui
