### ISSUE TITLE
ancombc2: Error in feature_table[tax_keep, , drop = FALSE] :    subscript out of bounds`

### ISSUE THREAD

**Issue by ibrila** [FrederickHuangLin/ANCOMBC#104]
Hi,

I had analyzed my data using `ancomb` function and now wanted to use `ancombc2` as I want to do pairwise comparisons. However, when I try running the function, I get the following error:

> Error in feature_table[tax_keep, , drop = FALSE] :  subscript out of bounds

I used the same `phyloseq` object I successfully used in `ancombc`. So I'm not sure what the issue is.

The call:

```
DA_ancombc2 <- ancombc2(
  data = ps,
  fix_formula = "var1 + var2 + var3",
  prv_cut = 0,
  pairwise = TRUE,
  rand_formula = "1 | var4",
  group = "var1",
  struc_zero = TRUE,
  neg_lb = TRUE)
```

Tinkering a bit more revealed that `ancombc2` seems to run if I omit the `struc_zero` argument. However after >10 hours of running it giver error: `Error in dimnames(x) <- dn :  length of 'dimnames' [2] not equal to array extent`

**Comment by ibrila** [comment]
I have now tinkered a bit more and noticed that `ancombc2` seems to run if I omit the `struc_zero` argument.

**Comment by FrederickHuangLin** [comment]
Hi @ibrila,

Thanks for your feedback! 

Unfortunately, I am not able to reproduce the error message you saw. Could you try assigning a value to `tax_level`? Available options can be seen by checking `colnames(tax_table(ps))`. For instance, you can set `tax_level = "Family"`.

If it does not work, would you mind sharing your data (with all sensitive information removed) with me to look into the problem? For instance, replace subject IDs with a dummy variable, change covariate names to some meaningless names (`var1`, `var2`, ..., as you did here), etc. You can send the dummy data to my E-mail at huang.lin@nih.gov (make sure the dummy data can reproduce the error message you encountered)

Also, running the mixed-effects model can be time-consuming since the estimates for each taxon has to be obtained iteratively. Try using parallel computing by setting the `n_cl` argument in `ancombc2` can substantially reduce the computing time.

Best,
Huang

**Comment by jylee324** [comment]
Hi, @FrederickHuangLin

I had the same problem.

Input file format is phyloseq object.

The call: 
```javascript
ancombc2(
  data = phyloseq, assay_name = "counts", tax_level = "Genus", 
  fix_formula = "var1", rand_formula = NULL, p_adj_method = "BH", pseudo = 0, pseudo_sens = TRUE,
  prv_cut = 0.1, lib_cut = 1000, s0_perc = 0.05, group = target.col, struc_zero = TRUE, neg_lb = TRUE, alpha = 0.05,
  n_cl = 1, verbose = TRUE, global = FALSE, pairwise = FALSE, dunnet = FALSE, trend = FALSE,
  iter_control = list(tol = 0.01, max_iter = 20, verbose = FALSE),
  em_control = list(tol = 1e-05, max_iter = 100),
  mdfdr_control = list(fwer_ctrl_method = "holm", B = 100),
  trend_control = list(contrast = NULL, node = NULL, solver = "ECOS", B = 100)
)
```
Error message:
`Error in feature_table[tax_keep, , drop = FALSE] : 
  subscript out of bounds`

The error occurred when tax level is "Genus", but not at higher tax levels (e.g. "Phylum", "Family").

In detail, error occurred during `data_core()` function

https://github.com/FrederickHuangLin/ANCOMBC/blob/d54944ea42b3f1889f181fb20b64e49c9f4c7eca/R/ancombc_prep.R#L108-L113

To check why this code raised error, I ran source code of `ancombc2()` one by one.
**And found weird taxonomy names in `tax_keep` variable 
(e.g. `"X.Clostridium._methylpentosum_group", "X.Eubacterium._oxidoreducens_group"`).**

However, when I checked `tax_table()` in the input phyloseq object data, the original taxonomy names are **`"[Clostridium]_methylpentosum_group"` and `"[Eubacterium]_oxidoreducens_group"`.**

As I examined, these distortion in taxonomy names (e.g. `[Eubacterium]_oxidoreducens_group` to `X.Eubacterium._oxidoreducens_group`) occurred in `get_struc_zero()` function. 
https://github.com/FrederickHuangLin/ANCOMBC/blob/d54944ea42b3f1889f181fb20b64e49c9f4c7eca/R/ancombc_prep.R#L275
The square brackets in taxonomy name is changed to `"X."` character, when `as.data.frame()` function is applied to `output` variable.

Taxonomy names with square brackets like "[Eubacterium]_oxidoreducens_group" are common in SILVA 138 database.

Thus, I think that the revision of `get_struc_zero()` function to maintain the original taxonomy names will prevent the error that occurred with the SILVA taxonomy name.

If you don't mind, could you check this part?

Best,

**Comment by FrederickHuangLin** [comment]
Hi @jylee324,

Thanks for your feedback! I greatly appreciate it!

I am looking into the problem, and it seems `as.data.frame()` would not coerce the square brackets in the taxonomy name to  `X.` from my end. 

I wonder if different R version handles `as.data.frame()` in different ways. If you don't mind, could you run the following toy example for me?

```
tmp = matrix(1:9, ncol = 3)
rownames(tmp) = c("[Clostridium]_methylpentosum_group", "A", "B")
colnames(tmp) = c("col1", "col2", "col3")
as.data.frame(tmp)
```

it shows 

```
                                   col1 col2 col3
[Clostridium]_methylpentosum_group    1    4    7
A                                     2    5    8
B                                     3    6    9
```
on my computer. 

Here is my session info:

```
R version 4.2.0 (2022-04-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur/Monterey 10.16
```

Best,
Huang

**Comment by jylee324** [comment]
Thank you for your help!

I ran your example code and got following result:
```
                                   col1 col2 col3
[Clostridium]_methylpentosum_group    1    4    7
A                                     2    5    8
B                                     3    6    9
```
In your example, `as.data.frame()` didn't distort row names with square brackets in my computer too.

I examined other possible reasons and found a suspicious taxa aggregation result in `tse_alt` object.

https://github.com/FrederickHuangLin/ANCOMBC/blob/d54944ea42b3f1889f181fb20b64e49c9f4c7eca/R/ancombc2.R#L374-L380

Run:
```
taxa_names <- rowData(tse_alt) %>% rownames()
taxa_names[duplicated(taxa_names)]
```
Result:
```
[1] "Unclassified_Peptostreptococcales-Tissierellales"
```

This result suggests that duplicated row name is generated in `tse_alt` object when aggregating ASV to genus level.

And removal of one of the rows which have duplicated name prevented distortion of the row names in the following part (That is, the square brackets in the taxa names were maintained, and `X.` character was not added after `as.data.frame()` function):
https://github.com/FrederickHuangLin/ANCOMBC/blob/d54944ea42b3f1889f181fb20b64e49c9f4c7eca/R/ancombc_prep.R#L275

I have no idea why the taxa aggregation proccess results in such duplicated taxa names.

Here is my session info:
```
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=Korean_Korea.utf8  LC_CTYPE=Korean_Korea.utf8    LC_MONETARY=Korean_Korea.utf8 LC_NUMERIC=C                 
[5] LC_TIME=Korean_Korea.utf8    

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] mia_1.4.0                      MultiAssayExperiment_1.22.0    ANCOMBC_1.6.3                  glue_1.6.2                    
 [5] forcats_0.5.2                  stringr_1.4.1                  dplyr_1.0.10                   purrr_0.3.5                   
 [9] readr_2.1.3                    tidyr_1.2.1                    tibble_3.1.8                   tidyverse_1.3.2               
[13] RColorBrewer_1.1-3             vegan_2.6-2                    lattice_0.20-45                permute_0.9-7                 
[17] ggtree_3.4.4                   qiime2R_0.99.6                 speedyseq_0.5.3.9018           microbiome_1.18.0             
[21] ggplot2_3.3.6                  TreeSummarizedExperiment_2.4.0 Biostrings_2.64.1              XVector_0.36.0                
[25] SingleCellExperiment_1.18.1    SummarizedExperiment_1.26.1    Biobase_2.56.0                 GenomicRanges_1.48.0          
[29] GenomeInfoDb_1.32.4            IRanges_2.30.1                 S4Vectors_0.34.0               BiocGenerics_0.42.0           
[33] MatrixGenerics_1.8.1           matrixStats_0.62.0             phyloseq_1.40.0               

```

Best,

**Comment by FrederickHuangLin** [comment]
Thanks, @jylee324!

Thanks for your feedback!

It seems the problem was inherited from the `SummarizedExperiment` object. I think I have to ditch the row name idea to get around this issue. I am working on it now and will push a bug-fix change by tomorrow.

I will keep you posted.

Thanks,
Huang

**Comment by FrederickHuangLin** [comment]
Hi @ibrila  & @jylee324 ,

I have updated the package accordingly to resolve the bug. You can try it by downloading the devel version of `ANCOMBC` from GitHub.

Please note that the Bioconductor branch RELEASE_3_15 is now frozen, so there will be no update of `ANCOMBC` there. New features of `ANCOMBC` will be available on the Bioconductor branch RELEASE_3_16 (in early November).

Thanks for your support to `ANCOMBC`!

Best,
Huang

**Comment by jylee324** [comment]
Thanks a lot! 

It works very well!
