### ISSUE TITLE
question regarding interpreting ancom results' directionality

### ISSUE THREAD

**Issue by tommyfuu** [FrederickHuangLin/ANCOMBC#108]
Hi,

I was able to run the ancom function (not ancombc) for my analyses, but I am slightly confused regarding which level it uses among the levels for the `main_var` as its reference level to determine the "positive" and "negative" directions in Section 3.3 of [this tutorial](https://www.bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOM.html). More specifically, if I have my `main_var` represented by two levels "treatment" and "baseline" in the metadata, how do I know if a "positive" biomarker in the `df_fig_w` dataframe of the tutorial is upregulated regarding "treatment" or "baseline"? How does this generalize to the case where there are more than 2 levels of `main_var`?

After briefly browsing [the code](https://github.com/FrederickHuangLin/ANCOMBC/blob/devel/R/ancom.R) for this I am still kind of confused so I would appreciate some help on that. Thank you!

**Comment by FrederickHuangLin** [comment]
Hi @tommyfuu,

In the example you gave, the reference level is "baseline", and the effect size is by comparing with the "baseline". If there are more than 2 levels, ANCOM is not able to tell the direction and the effect sizes given by `ancom` will always be positive. This is the limitation of ANCOM and also one of the motivations for us to develop ANCOM-BC.

For details on the reference levels, you can check section 3.1 of this [vignette](https://bioconductor.org/packages/devel/bioc/vignettes/ANCOMBC/inst/doc/ANCOM.html)

Best,
Huang
