### ISSUE TITLE
Compare coefficients with and without covariates

### ISSUE THREAD

**Issue by MjelleLab** [FrederickHuangLin/ANCOMBC#109]
I am comparing a cancer-normal groups `Group` and have additional covariates `Age`, `Sex`. I would like to run ANCOMBC twice, one with the covariates and one without, to see how much the covariates contribute the the main comparison which is cancer-normal. 

What are the coefficient that I should extract to get this information? The lfc and W does not seem to change when I include or exclude Age and Sex like below: 

out = ancombc2(data = data,struc_zero = T,pseudo_sens = TRUE,fix_formula = c("Group","Age","Sex"), 
               group="Group",prv_cut = 0.01,lib_cut = 0)

**Comment by FrederickHuangLin** [comment]
Hi @MjelleLab,

The `fix_formula` you specified is not correct. Please specify it as `fix_formula = "Group + Age + Sex"`

You can check section 4.2 of the [vignette](https://bioconductor.org/packages/devel/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC2.html) for an example.

Best,
Huang

**Comment by MjelleLab** [comment]
@FrederickHuangLin , thanks, actually the quotes was a typo in my question. But do you know how to get coefficients (effect sizes) with and without covariates. For instance one with fix_formula = c("Group +Age +Sex") and one with fix_formula = c("Group"). What output should I look for when comparing the effects of Age and Sex in this example?

**Comment by FrederickHuangLin** [comment]
Hi @MjelleLab,

You can run the two models separately. For instance,

```
out1 = ancombc2(data = data,struc_zero = T,pseudo_sens = TRUE,fix_formula = "Group + Age + Sex",
group="Group",prv_cut = 0.01,lib_cut = 0)
```

and

```
out2 = ancombc2(data = data,struc_zero = T,pseudo_sens = TRUE,fix_formula = "Group",
group="Group",prv_cut = 0.01,lib_cut = 0)
```

The effect sizes of `Group` with covariates adjustment are here: `out1$res`, columns starting with "lfc_Group" are the log fold changes of `Group` after covariates adjustment.

The effect sizes of `Group` without covariates adjustment are here: `out2$res`. Similarly, columns starting with "lfc_Group" are the log fold changes of `Group`.

Let me know if you have any additional questions.

Best,
Huang

**Comment by aimirza** [comment]
> Hi @MjelleLab,
> 
> The `fix_formula` you specified is not correct. Please specify it as `fix_formula = "Group + Age + Sex"`
> 
> You can check section 4.2 of the [vignette](https://bioconductor.org/packages/devel/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC2.html) for an example.
> 
> Best, Huang

@FrederickHuangLin In the vignette, the main variable of interest ("bmi") is listed last (after the covariates) whereas where you mention to list it ("Group") first. Which one is it?
