### ISSUE TITLE
Log fold change

### ISSUE THREAD

**Issue by ntromas** [FrederickHuangLin/ANCOMBC#11]
Hi,

Very naive question: I wonder if negative log-Fold change are conserved in ANCOMBC output.

Cheers,

**Comment by FrederickHuangLin** [comment]
Hi @ntromas,

Thanks for your question!

Yes, ANCOMBC will output negative log-fold changes. Section 3.4.1 of this [vignette](https://bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC.html#ancombc-global-test-result) shows an example of `beta`value output and it contains both positive and negative values.

Best,
Frederick

**Comment by benyoung93** [comment]
Good afternoon 
Apologies for this probably simple question, but the beta output gives negative and positive LFC. Is this therefore a log-fold change, or a log-2-fold change. 

This is always one of those things I look up, learn, and forget but just wanted to double check to make sure I am using correct terminology in writing of my results. 

Thank you for the help and apologies for the simple query. 
Benjamin

**Comment by FrederickHuangLin** [comment]
Yes, it is log-fold change but in natural base, i.e., log(e)-fold change.

Huang
