### ISSUE TITLE
Issues in ANCOM-BC2 vignette tutorial

### ISSUE THREAD

**Issue by f-Enzo** [FrederickHuangLin/ANCOMBC#112]
Hello, 
There are several difficulties to run the ANCOM-BC2 tutorials in the vignette :
https://github.com/FrederickHuangLin/ANCOMBC/blob/devel/vignettes/ANCOMBC2.Rmd

First, all required packages are not specified (for example "dplyr" for the pipes).
Second, there is an error when running this part of the code:

sens_cat = tab_sens %>%
    transmute(taxon, sens_cat = cat_cov2) %>%
    left_join(res_prim %>%
                  transmute(taxon, diff_cat = diff_cat_cov2), 
              by = "taxon") %>%
    mutate(group = "Cat2 vs. Cat1") %>%
    bind_rows(
        tab_sens %>%
            transmute(taxon, sens_cat = cat_cov3) %>%
            left_join(res_prim %>%
                          transmute(taxon, diff_cat = diff_cat_cov3), 
                      by = "taxon") %>%
            mutate(group = "Cat3 vs. Cat1")
    )
The variable taxon does not exist so the code does not work.
 Kind regards,

**Comment by FrederickHuangLin** [comment]
Hi @f-Enzo,

Which version of `ANCOMBC` are you using? 

Since `ANCOMBC` 2.0.x, `tab_sens` contains a column name of `taxon`.

Also, `dplyr` is imported by `tidyverse` in line 19: https://github.com/FrederickHuangLin/ANCOMBC/blob/devel/vignettes/ANCOMBC2.Rmd#L19

Best,
Huang

**Comment by f-Enzo** [comment]
Hi, 
My bad for the packages, I was looking at the Bioconductor version of the tutorial.
Indeed my version of the package is 1.6.4...
Thank you very much
