### ISSUE TITLE
Compatibility with BIOM objects

### ISSUE THREAD

**Issue by f-Enzo** [FrederickHuangLin/ANCOMBC#118]
Hello,
The package rbiom (https://rdrr.io/github/cmmr/rbiom/man/rbiom.html) looks more performant than phyloseq to read BIOM data in R. However it generates a BIOM class object. I wonder if it is possible to use this object as input in ancombc2  or if you planned to make it possible. 
Sincerely,

Enzo

**Comment by FrederickHuangLin** [comment]
Hi @f-Enzo,

The answer is a big "YES"!

You can generate a `tse` object by importing the BIOM data. For details, see this [tutorial](https://microbiome.github.io/OMA/containers.html#import-from-external-files). After creating the `tse` object, you can feed it to the `ancombc` or `ancombc2` function.

Best,
Huang
