### ISSUE TITLE
Error: Estimation failed for the following covariates:

### ISSUE THREAD

**Issue by FMirandaSanchez** [FrederickHuangLin/ANCOMBC#119]
Hi Huang,

I have a phyloseq object (physeqExp1c) of 16S sequences, I want to compare 3 groups in the "Condition" column of my metadata (Bead, Liquid, and Source -reference group-), however, I have as covariants the Media and the Week the sequences are coming from (Media factors: TSBY, TSB and, Inoculum; Week factors: 0,1,5). Trying to run ancombc2  I haven't being able to incorporate the effects of the covariates (If I use only  "Condition" or other column in the fix_fomula field the analysis runs smoothly). I think I am not stating the fix formula correctly or maybe it is something else, could you give it a look?

Thanks a lot in advance!
F
_______________
This is how the phyloseq object looks like:
`physeqExp1c`

phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 317 taxa and 18 samples ]
sample_data() Sample Data:       [ 18 samples by 12 sample variables ]
tax_table()   Taxonomy Table:    [ 317 taxa by 7 taxonomic ranks ]

After running the following command:
```
outBC2_WCM_Exp1 = ancombc2(data = physeqExp1c, struc_zero = F,pseudo_sens = TRUE, fix_formula = " Condition + Week + Media",rand_formula = NULL, group="Condition",prv_cut = 0.01,lib_cut = 1000)
```
I get:
Error: Estimation failed for the following covariates:
Week5, MediaTSBY
Consider removing these covariates

Something similar happens If I try:
```
outBC2_CM_Exp1 = ancombc2(data = physeqExp1c, struc_zero = F, pseudo_sens = TRUE, fix_formula = "Condition + Media",
rand_formula = NULL, group="Condition",prv_cut = 0.01,lib_cut = 1000)
```
Error: Estimation failed for the following covariates:
MediaTSBY
Consider removing these covariates

And last but not least:
```
outBC2_CW_Exp1 = ancombc2(data = physeqExp1c, struc_zero = F, pseudo_sens = TRUE, fix_formula = "Condition + Week",
rand_formula = NULL, group="Condition",prv_cut = 0.01,lib_cut = 1000)
```

I get:
Error: Estimation failed for the following covariates:
Week5
Consider removing these covariates

________
this I how the factors of the phyloseq object look like:
> levels(sample_data(physeqExp1c)$Media)
[1] "Inoculum" "TSB"      "TSBY"    
> levels(sample_data(physeqExp1c)$Week)
[1] "0" "1" "5"
> levels(sample_data(physeqExp1c)$Condition)
[1] "Source" "Liquid" "Bead"

**Comment by FrederickHuangLin** [comment]
Hi @FMirandaSanchez,

This message shows that there is not enough degree of freedom to estimate these covariates. Could you verify it by running the following

```
lm(y ~ Condition + Week + Media, data = data.frame(y = abundance(physeqExp1c)[1, ], meta(physeqExp1c)))
```

basically, test if the linear regression can be run by using the abundances of the first taxon. You should see missing coefficients for `Week` and `Media`.

The potential reasons are:
1. `Week` and `Media` contain missing values
2. `Week` and `Media` are highly correlated with `Condition`

Best,
Huang
