### ISSUE TITLE
adjusting for random effects

### ISSUE THREAD

**Issue by KMKemp** [FrederickHuangLin/ANCOMBC#12]
Really nice contribution to the field. I am trying ANCOMBC with my own dataset. Is there currently a way to adjust for random effects as with ANCOM-II? I use the `rand_formula = "~ 1 | random_effect_var"` option with ANCOM-II.

**Comment by FrederickHuangLin** [comment]
Hi @KMKemp,

Thanks for your interest in using ANCOMBC!

The current version of ANCOMBC is able to perform covariates adjustment and global tests as mentioned in its paper. However, the mixed effects model is currently not available, but we are drafting the paper about it. We will add the corresponding functions to the ANCOMBC package once the new paper gets published.
 
Stay tuned!
Frederick
