### ISSUE TITLE
input relative abundance?

### ISSUE THREAD

**Issue by Brandi161** [FrederickHuangLin/ANCOMBC#120]
Dear Frederick,

First of all thank you for the wonderful programs for microbiome analysis!

Is it possible to use a relative abundance table as input for ancombc? I am asking because I am using taxonomic output from a software (Metaphlan) which only provides relative abundance data. 

Best,
Brandi

**Comment by CR7-Marchal** [comment]
>How about multiplied by read depth? As mentioned by [https://waldronlab.io/curatedMetagenomicDataAnalyses/articles/NUI-Galway-Metagenomics-Workshop.html](url).
It seems reasonable, though I could not completely understand.

**Comment by FrederickHuangLin** [comment]
Hi @Brandi161,

Unfortunately, ANCOMBC does not support relative abundances as the input data. 

Metaphlan 3 can also generate absolute count data. See [here](https://forum.biobakery.org/t/to-get-the-absolute-counts-of-each-taxa/2092). Also, multiplying by the sequencing depth could be an option, as mentioned by @CR7-Marchal .

Best,
Huang
