### ISSUE TITLE
ANCOM-BC vs ANCOM-BC2

### ISSUE THREAD

**Issue by stangedal** [FrederickHuangLin/ANCOMBC#123]
Hi,
I need to rerun some analyses performed before the new version of ANCOM and I am not able to do so. I am told ANCOM-BC is deprecated. Is there a way to perform analyses as they were in ANCOM-BC also after downloading ANCOM-BC2?

Solveig

**Comment by FrederickHuangLin** [comment]
Hi @stangedal,

You can still run `ancombc`. The warning message is trying to suggest using `ancombc2` instead but will not stop you from using `ancombc`.

Best,
Huang

**Comment by stangedal** [comment]
OK - that is strange - it failed when trying to run my commands generated before the update. Was able to get the old version from a friend so it worked out ok :)
