### ISSUE TITLE
Structural zeroes, q-value of 0.000 but taxa present in both groups?

### ISSUE THREAD

**Issue by MushroomToast** [FrederickHuangLin/ANCOMBC#124]
I have been looking through the conversations discussing taxa allocated as significantly different with p/q values and SE of 0 and just wanted to ask a follow up question. 

Although examples suggest that this occurs when taxa are present in only one group, when I look at my taxa bar plot generated via qiime, I see that taxa allocated as significant _are_ present in both groups. 

Am I missing some sort of transformation or cleaning process occurring in the methods where taxa are identified as structural zeroes even though they are present in both groups (but reduced in one?)

Thanks very much for your help

**Comment by FrederickHuangLin** [comment]
Hi @MushroomToast,

You are using `ancombc`, right? If you turn on `neg_lb = TRUE`, it will classify a taxon as a structural zero using its asymptotic lower bound, in this case, it is not necessary for a structural zero taxon to be completely absent from one group. You can check page 7 in the user manual [here](https://www.bioconductor.org/packages/release/bioc/manuals/ANCOMBC/man/ANCOMBC.pdf).

Best,
Huang
