### ISSUE TITLE
questoin: ANCOMBC for predicted functional data

### ISSUE THREAD

**Issue by carlosmandoz** [FrederickHuangLin/ANCOMBC#126]
Hello,

I do not report an issue here but have a question: Is it appropriate to use ANCOM-BC to perform differential abundance analysis of the KOs from picrust2 output? Unlike the ASV/OTU table, this is a floating point number. 

Thanks

**Comment by cafferychen777** [comment]
Hello,

I am developing a R package to compare and visualize the difference abundance of picrust2 output files which hope to contain all the mainstream DA method. If you are interested, you can follow my github or through my email cafferychen7850@gmail.com.

Thanks

**Comment by cafferychen777** [comment]
> Hello,
> 
> I do not report an issue here but have a question: Is it appropriate to use ANCOM-BC to perform differential abundance analysis of the KOs from picrust2 output? Unlike the ASV/OTU table, this is a floating point number.
> 
> Thanks

Hello,

I am developing a R package to compare and visualize the difference abundance of picrust2 output files which hope to contain all the mainstream DA method. If you are interested, you can follow my github or through my email [cafferychen7850@gmail.com](mailto:cafferychen7850@gmail.com).

Thanks

**Comment by FrederickHuangLin** [comment]
Hi @carlosmandoz,

I think so long as you believe your data are compositional (have a total sum constraint), you can use ANCOM-BC or ANCOM-BC2. 

Also, thanks @cafferychen777 for your input!

Best,
Huang

**Comment by cafferychen777** [comment]
> 

Thank you for your question about the appropriateness of using ANCOM-BC for differential abundance analysis of KOs from PICRUSt2 output. While I cannot provide a definitive answer to your question, I would like to introduce ggpicrust2 as a potential solution. ggpicrust2 is a user-friendly R package specifically designed for PICRUSt2 predicted functional profile analysis and visualization. It provides advanced differential abundance analysis methods and visualization capabilities for PICRUSt2 output data, and supports multiple differential abundance analysis methods including ALDEx2, DEseq2, Maaslin2, edgeR, limma voom, metagenomeSeq, and lefser. I recommend checking out the features and capabilities of ggpicrust2, which can be found on its GitHub page along with detailed usage documentation.

**Comment by FrederickHuangLin** [comment]
Hi @cafferychen777,

Thanks for your update!

May I ask if you have plans for incorporating ANCOM-BC and ANCOM-BC2 into your `ggpicrust2`? It would be great if we can make it happen! Let me know if I can be of any help.

Best,
Huang

**Comment by cafferychen777** [comment]
Hi Huang,

Thank you for reaching out and your kind words. Yes, we do have plans to
incorporate ANCOM-BC and ANCOM-BC2 into ggpicrust2. We believe it will be a
valuable addition and we appreciate your interest in this feature.

Thank you for offering your help, we will keep that in mind as we work on
this. We will keep you updated on our progress and please let us know if
you have any further questions or suggestions.

Best regards,
Chen YANG


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
23/03/29
下午02:33:59

Frederick Huang Lin ***@***.***> 于2023年3月29日周三 01:54写道：
