### ISSUE TITLE
Running ancombc2 on agglomerated data?

### ISSUE THREAD

**Issue by gabrielet** [FrederickHuangLin/ANCOMBC#128]
If I run `ancombc2()` on an agglomerated dataset, i.e. the result of using the function `tax_glom()` from the _phyloseq_ package, i might end up with less than 50 taxa (for example at Phylum level).

At that point, I will see this warning:

> The number of taxa used for estimating sample-specific biases is: n
> A large number of taxa (>50) is required for the consistent estimation of biases 

Question is: how worried should I be, regarding the biases estimation?

If I should be worried, what is the suggested approach to investigate differential abundance at a specific taxonomic level?

**Comment by FrederickHuangLin** [comment]
Hi @gabrielet,

If you specify `ancombc2` as follows:

```
ancombc2(
data = otu_data,
assay_name = "counts",
tax_level = "Phylum",
...
)
```

`ancombc2` will perform the bias correction using the raw data (OTU level data, usually contain thousands of OTUs) and make the inference at your specified level, which is the phylum level here.

Best,
Huang

**Comment by gabrielet** [comment]
@FrederickHuangLin ok, thank you! i was confused by the help of `ancombc2()` since it reports that: 

> tax_level: character. The taxonomic level of interest. The input data
> can be agglomerated at different taxonomic levels based on
> your research interest. Default is NULL, i.e., do not perform
> agglomeration, and the ANCOM-BC2 anlysis will be performed at
> the lowest taxonomic level of the input ‘data’.

I thought the agglomeration should be performed in advance but you confirmed that's not the case.

**Comment by FrederickHuangLin** [comment]
Thanks for pointing it out! I will polish the user manual to make it clearer.
