### ISSUE TITLE
Error message "cannot open the connection" (socketConnection)

### ISSUE THREAD

**Issue by khb3850** [FrederickHuangLin/ANCOMBC#130]
Hello, 

I'm Hanbeem Kim.

When I'm running the ANCOM-BC, I got the error message.
Error message
-------------------------------------------------------------------------------------------------
'ancombc' is deprecated 
Use 'ancombc2' instead
Error in socketConnection("localhost", port = port, server = TRUE, blocking = TRUE,  : 
  cannot open the connection
In addition: Warning message:
In socketConnection("localhost", port = port, server = TRUE, blocking = TRUE,  :
  port 11956 cannot be opened
--------------------------------------------------------------------------------------------------
Actually, the code that I run worked even three days ago.

Can you give me any suggestions?

Thank you in advance.

Hanbeen Kim.

**Comment by FrederickHuangLin** [comment]
Hi @khb3850,

The warning message you saw is likely that the `ancombc2` was stopped manually earlier. This is not a warning message from `ancombc2` but from the `parallel` computing procedure. You can run the following function to solve the issue

```
unregister_dopar <- function() {
  env <- foreach:::.foreachGlobals
  rm(list=ls(name=env), pos=env)
}
```
or simply restart your RStudio or R.

A related issue is [here](https://github.com/FrederickHuangLin/ANCOMBC/issues/116).

Best,
Huang
