### ISSUE TITLE
Running ANCOMBC problems with binomial variables

### ISSUE THREAD

**Issue by marco2985** [FrederickHuangLin/ANCOMBC#131]
Hi,
I am actually trying to run ANCOMBC from a phyloseq object but I always get the same error message and I do not know what is the problem. I want to see the difference bacterial abundance between individuals with different MHC class II supertypes. I have 4 different supertypes and the data is just if the individuals carry the supertype or not (0,1). I am not sure how many argument I have to use to make it run as simple as possible. I have always use Deseq2 for microbiome data and it has worked good for me but it seems more appropiate the use of ANCOMBC...

Here it is the code that I use: 
library("phyloseq")
library("ggplot2")      # graphics
library("readxl")       # necessary to import the data from Excel file
library("dplyr")        # filter and reformat data frames
library("tibble")       # Needed for converting column to row names
library ("microbiome")
library(ANCOMBC)
library("mia")

otu_mat<-read.delim("otu_tableAbundance.txt")
tax_mat<-read.delim("tax_table_seq.txt")
samples_df<-read.delim("Metadata_Supertype4_V2_MHC.txt")

####define the row names from the otu column
otu_mat <- otu_mat %>%
  tibble::column_to_rownames("otu") 

tax_mat <- tax_mat %>% 
  tibble::column_to_rownames("otu")

samples_df <- samples_df %>% 
  tibble::column_to_rownames("sample")

##Transform into matrixes otu and tax tables (sample table can be left as data frame)
otu_mat <- as.matrix(otu_mat)
tax_mat <- as.matrix(tax_mat)

###Transform to phyloseq objects

OTU = otu_table(otu_mat, taxa_are_rows = TRUE)
TAX = tax_table(tax_mat)
samples = sample_data(samples_df)
samples
ps <- phyloseq(OTU, TAX, samples)
ps

Therefore, the object will be ps. I transformed into compositional data

(ps_com <- microbiome::transform(ps, "compositional")) 

out = ancombc2(phyloseq = ps_com, formula = "supertype4",
              p_adj_method = "holm", prv_cut = 0.10, lib_cut = 1000,
              group = "bmi_group", struc_zero = TRUE, neg_lb = FALSE,
              tol = 1e-5, max_iter = 100, conserve = TRUE,
              alpha = 0.05, global = TRUE, n_cl = 1, verbose = TRUE)

The error message is the following: 
Error in ancombc2(data = NULL, assay_name = NULL, phyloseq = ps_clr, formula = "supertype4",  : 
  unused arguments (phyloseq = ps_clr, formula = "supertype4", tol = 1e-05, max_iter = 100, conserve = TRUE)

Thank you very much,

**Comment by FrederickHuangLin** [comment]
Hi @marco2985,

The correct syntax should be `data = ps_com` instead of `phyloseq = ps_com`. That should solve the error.

Best,
Huang
