### ISSUE TITLE
Code fixes for sparse_linear and sparse_dist

### ISSUE THREAD

**Issue by hlk-slowlearner** [FrederickHuangLin/ANCOMBC#133]
Hello@FrederickHuangLin , thank you for developing this package to a great extent to meet my scientific research needs. However, I found some problems in the process of using secom, the situation is this: I performed secom_linear and secom_dist analysis on two phyloseq objects respectively. One of the ps objects ran successfully, while the other produced the following error:
>  Error in `diag<-`(`*tmp*`, value = colSums(mat_occur)): replacement diagonal has wrong length
> Traceback:
> 
> 1. from_ps_to_network(rt_ps)
> 2. secom_linear(data = list(ps), pseudo = 0, prv_cut = 0.02, lib_cut = 500, 
>  .     corr_cut = 0.5, wins_quant = c(0.05, 0.95), method = "spearman", 
>  .     soft = FALSE, thresh_len = 20, n_cv = 10, thresh_hard = 0.1, 
>  .     max_p = 0.005, n_cl = 2)   # at line 8-13 of file <text>
> 3. sparse_linear(mat = t(y_hat), wins_quant, method, soft, thresh_len, 
>  .     n_cv, thresh_hard, max_p)
> 4. `diag<-`(`*tmp*`, value = colSums(mat_occur))
> 5. stop("replacement diagonal has wrong length")

 After careful investigation of the problem, I found that the reason is a small part(line 49-55) of the function sparse_linear (and sparse_dist) code:

```
  df_occur = as.data.frame(mat_occur) %>%
        tibble::rownames_to_column("sample_id") %>%
        tidyr::pivot_longer(cols = -.data$sample_id, names_to = "taxon",
                            values_to = "occur") %>%
        dplyr::filter(.data$occur == 1)

    mat_cooccur = crossprod(table(df_occur[, seq_len(2)]))
```

Because in the process of generating the co-occurrence matrix, mat_cooccur lost the 8 isolated taxas of mat_occur (they have not coexisted with other groups, and this is an extremely rare situation, we should exclude these nodes in the subsequent analysis but in this process they cause the error). In order to avoid this error, I changed this part of the code. Of course, as a novice who is not familiar with this package, I believe there will be a more elegant and simple way to avoid this rare error, the following is my approach:
1. I first changed part of the code of saprse_linear, and name this new function "sparse_linear1"：
```
   ###changed code
    df_occur_0 = as.data.frame(mat_occur) %>%
        tibble::rownames_to_column("sample_id") %>%
        tidyr::pivot_longer(cols = -.data$sample_id, names_to = "taxon",
                            values_to = "occur") 
    df_occur=dplyr::filter(df_occur_0,df_occur_0$occur ==1) 
     
    mat_cooccur = crossprod(table(df_occur[, seq_len(2)]))           
    ###changed code     
    misstaxa=c()
    for (i in colnames(mat_occur)){
        if(!i %in% colnames(mat_cooccur)){
            misstaxa=c(misstaxa,i)
            }
    }
    df_misstaxa=df_occur_0[df_occur_0$taxon%in%misstaxa,]
    df_occur=rbind(df_occur,df_misstaxa)
    mat_cooccur = crossprod(table(df_occur[, seq_len(2)]))
```
2.  Next I declared this function and temporarily replaced the original function in the namespace：
`environment(sparse_linear1) <- asNamespace('ANCOMBC')
assignInNamespace("sparse_linear", sparse_linear1, ns = "ANCOMBC")`
3. Finally, I re-ran secom_linear and avoided the error as I wished
4. A similar approach also be applied to secom_dist

Although I finally solved my own problem——actually I'm not sure——since I don't fully understand the details and full meaning of these codes, I still hope you can give me some advice (I'm not sure if I'm doing it right, and there must be a more elegant solution method).

look forward to your reply : )

**Comment by FrederickHuangLin** [comment]
Hi @hlk-slowlearner,

Thank you very much for your feedback and your efforts in making the `secom` function more bugless!

Could you share with me the version of `ANCOMBC` package that you are using? I have a very tight schedule this month but I will look into the problem and get back to you early next month.

Thank you,
Huang

**Comment by hlk-slowlearner** [comment]
已收到您的来信，会尽快回复

**Comment by hlk-slowlearner** [comment]
> Hi @hlk-slowlearner,
> 
> Thank you very much for your feedback and your efforts in making the `secom` function more bugless!
> 
> Could you share with me the version of `ANCOMBC` package that you are using? I have a very tight schedule this month but I will look into the problem and get back to you early next month.
> 
> Thank you, Huang

I found the version of this package as 2.0.2 in the DESCRIPTION document at the following path:
`/Library/Frameworks/R.framework/Versions/4.2/Resources/library/ANCOMBC/DESCRIPTION`
Thank you for taking time out of your busy schedule to reply, looking forward to your reply again！ ：)

**Comment by FrederickHuangLin** [comment]
Hi @hlk-slowlearner,

I was looking into the problem you encountered and was not able to reproduce the error. Could you help me create a reproducible example to deal with this problem?

For instance, I created the following occurrence matrix:
```
mat_occur = matrix(1, nrow = 4, ncol = 4)
colnames(mat_occur) = paste0("T", 1:4)
rownames(mat_occur) = paste0("S", 1:4)
mat_occur[1, 2:4] = 0
mat_occur[2:4, 1] = 0
```

The `mat_occur` looks like
```
  T1   T2   T3   T4
S1 1    0    0    0
S2 0    1    1    1 
S3 0    1    1    1
S4 0    1    1    1
```
As you can see, the taxon `T1` does not cooccur with other taxa. However, running the following lines created a correct co-occurrence matrix
```
df_occur = as.data.frame(mat_occur) %>%
        tibble::rownames_to_column("sample_id") %>%
        tidyr::pivot_longer(cols = -.data$sample_id, names_to = "taxon",
                            values_to = "occur") %>%
        dplyr::filter(.data$occur == 1)

mat_cooccur = crossprod(table(df_occur[, seq_len(2)]))
diag(mat_cooccur) = colSums(mat_occur)
```

`mat_cooccur` looks like the following.
```
  T1   T2   T3   T4
T1 1    0    0    0
T2 0    3    3    3 
T3 0    3    3    3
T4 0    3    3    3
```

As you can see, all taxa showed up.

Did I misunderstand your issue? Otherwise, may you provide some insights to reproduce the error?

Thank you,
Huang

**Comment by hlk-slowlearner** [comment]
已收到您的来信，会尽快回复

**Comment by FrederickHuangLin** [comment]
Hi @hlk-slowlearner,

A new version of ANCOMBC 2.0.3 will be pushed over this weekend to address the issue you raised. Please feel free to test it out. Again, thank you for helping improve the ANCOMBC package.

Best,
Huang
