### ISSUE TITLE
Missing values in the covariates

### ISSUE THREAD

**Issue by indrikwijaya** [FrederickHuangLin/ANCOMBC#136]
Hi, thank you for this great method! 

My question is on how ANCOM-BC treats covariates that have missing values. For instance, let's say my metadata looks like this
![image](https://user-images.githubusercontent.com/28745759/211476610-6bd85cdc-df76-4cfc-941d-4dc3fc228748.png)

I want to run ANCOM-BC on my continuous predictor, which is `Age` in this case. So, my formula will be `Age + Sex + BMI` and I won't specify the `group` argument, just like mentioned here #52 . 

In my metadata, `Cohort C` has missing information (`NA` values) for `Sex` and so will it be ignored totally just like how `glm` ignores rows with any `NA` values in the columns? Thank you!

**Comment by FrederickHuangLin** [comment]
Hi @indrikwijaya,

Yes, you are right! The internal regression models in `ancombc` and `ancombc2` are constrained to include only rows where all values are present (the default `na.omit` behavior).

Best,
Huang

**Comment by indrikwijaya** [comment]
Thanks for the reply!
