### ISSUE TITLE
how to perform multiple test for a multilevel factor?

### ISSUE THREAD

**Issue by gabrielet** [FrederickHuangLin/ANCOMBC#141]
Say i have the following model:

```
 fixedf <- "Treatment * TimePoint"
 randf <- "(1|CollectionSite)"
```

where:
- two levels for Treatment: W or C. reference level set at C;
- three levels for TimePoint: June, July, and August. reference level set at June;
- two levels for DNA_RNA: DNA and RNA. reference level set at DNA.

then i run `ancombc2()`, using the group option set for TimePoint.

 `ancombc2(data=phylo_data, assay_name="counts", tax_level=taxa_level, fix_formula=fixedf, rand_formula=randf, group="TimePoint", p_adj_method="fdr", n_cl = 8, verbose=T)`
 
The goal here would be to compare June-July, July-August, and June-August but it seems that the specification I used is not doing what I expect.

I looked into the `ancombc2()` vignette and the same is happening there, i.e. the bmi analysis shows comparisons for obese-lean and obese-overweight, if I got it right.

So, what if I want to do the multiple comparisons of all the levels in a factor? What's the approach to this analysis? Or is it not feasible?

**Comment by FrederickHuangLin** [comment]
Hi @gabrielet,

I think the pairwise test in `ancombc2` could be the feature that you are looking for. For details, you can check section 4.7 in the [vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC2.html).

Best,
Huang

**Comment by gabrielet** [comment]
@FrederickHuangLin, yes I think that is the case. i will look into this document you shared. My bad, I missed it in the github vignette.

**Comment by gabrielet** [comment]
@FrederickHuangLin, yes I think that is the case. but still is not very clear to me how you put all togheter.
so...is this an _a-posteriori_ analysis? If I have to guess this is what I think it happens:
the output you're using in 4.7 is coming from the section 4.2. however, in 4.2 when you run ANCOMBC2, the group factor is not defined, yet. in fact, you're using a grouping variable called **bmi** which, by itself, contains the groups 'lean', 'overweight', and 'obese'.
so, i think that you set `pairwise=T`, in 4.2, to perform the pairwise comparison between all the factors in **bmi**, correct? only then you are able to reorganise the results as you show in 4.7. am i right?

what is weird, when i run my analysis is that i don't get the pairwise comparisons as expected. this is what I do, after adding the `pairwise=T`

```
ancombc2(data=phylo_xna, assay_name="counts", tax_level=taxa_level, fix_formula=fixedf, rand_formula=randf, group="TimePoint", pairwise=T, p_adj_method="fdr", n_cl = 8, verbose=T)
```

the variable group is set as Timepoint which is a factor with three levels ($t_{1}$, $t_{2}$, and $t_{3}$), i.e. the three groups i want to compare, two at a time: $(t_{1}, t_{2})$,  $(t_{1}, t_{3})$, and  $(t_{2}, t_{3})$.

however, after running ANCOMBC2 as i just showed, what i get is the following:

```
> colnames(ancom_output[[abc]]$res_pair)[grep("diff", colnames(ancom_output[[abc]]$res_pair))]
 [1] "diff_TimePointJuly"                                      
 [2] "diff_TimePointAugust"                                    
 [3] "diff_TreatmentW:TimePointJuly"                           
 [4] "diff_TreatmentW:TimePointAugust"                         
 [5] "diff_TimePointAugust_TimePointJuly"                      
 [6] "diff_TreatmentW:TimePointJuly_TimePointJuly"             
 [7] "diff_TreatmentW:TimePointAugust_TimePointJuly"           
 [8] "diff_TreatmentW:TimePointJuly_TimePointAugust"           
 [9] "diff_TreatmentW:TimePointAugust_TimePointAugust"         
[10] "diff_TreatmentW:TimePointAugust_TreatmentW:TimePointJuly"
```

i am wondering whether there may be issues when i am using a formula containing the interaction, i.e. `Treatment*TimePoint` instead of using the two variables as independend, i.e. `Treatment+TimePoint`.

**Comment by FrederickHuangLin** [comment]
Hi @gabrielet,

Please see below my responses to your questions.

> so, i think that you set pairwise=T, in 4.2, to perform the pairwise comparison between all the factors in bmi, correct? only then you are able to reorganise the results as you show in 4.7. am i right?

You are absolutely right! If we do not specify `pairwise=T`, `ancombc2` will still correct the bias for the `group` variable (`bmi` in the vignette), but it will not perform multiple comparisons between `group` (including pairwise comparisons).

> i am wondering whether there may be issues when i am using a formula containing the interaction, i.e. Treatment*TimePoint instead of using the two variables as independend, i.e. Treatment+TimePoint.

Yes, that is the problem. Containing interaction terms in `fix_formula` will confuse the `ancombc2` multi-group comparisons. In that case, I recommend manually creating an interaction term. For instance, specifying `ancombc2` like `fixedf <- "Treatment + TimePoint + interaction"`, `group = "TimePoint"`, and `pairwise = T`.

I will create a Q&A session to clarify this issue in GitHub.

Best,
Huang

**Comment by gabrielet** [comment]
@FrederickHuangLin ok, this makes sense. thank you!
