### ISSUE TITLE
Receiving different result while conducting the pairwise function

### ISSUE THREAD

**Issue by ChihYingLu** [FrederickHuangLin/ANCOMBC#142]
Dear Huang,

I tried to analyze the taxa abundance differences between three groups (A, B, C) for my data by following your code in the ANCOM-BC-Code-Archive/scripts/figure_6_table_s1_s2_s3.Rmd. The result shows several taxa are significantly different between groups. However, when I try to do the task again with the ANCOMBC2 pairwise function, non of the taxa are significantly different between groups (all taxa's p and q values are 1), and their lfc value is also slightly different from the previous result (but pattern are the same). Below is the code I used for the two analyses. Do you have any idea what might be the cause? Thank you very much for your help!

1st analysis (ANCOM-BC-Code-Archive approach):
```
# Group A vs. B
out_AB = ancombc(data = tse_ab, assay_name = "counts",
               tax_level = "Phylum", phyloseq = NULL,
               formula = "group",
               p_adj_method = "holm", prv_cut = 0.10, lib_cut = 1000,
               group = "group", struc_zero = TRUE, neg_lb = TRUE,
               tol = 1e-5, max_iter = 100, conserve = TRUE,
               alpha = 0.05, global = TRUE, n_cl = 1, verbose = TRUE)
res_prim_AB_phylum = out_AB$res

# Group B vs. C
out_BC = ancombc(data = tse_bc, assay_name = "counts",
               tax_level = "Phylum", phyloseq = NULL,
               formula = "group",
               p_adj_method = "holm", prv_cut = 0.10, lib_cut = 1000,
               group = "group", struc_zero = TRUE, neg_lb = TRUE,
               tol = 1e-5, max_iter = 100, conserve = TRUE,
               alpha = 0.05, global = TRUE, n_cl = 1, verbose = TRUE)
res_prim_BC_phylum = out_BC$res

# Group A vs. C
out_AC = ancombc(data = tse_ac, assay_name = "counts",
               tax_level = "Phylum", phyloseq = NULL,
               formula = "group",
               p_adj_method = "holm", prv_cut = 0.10, lib_cut = 1000,
               group = "group", struc_zero = TRUE, neg_lb = TRUE,
               tol = 1e-5, max_iter = 100, conserve = TRUE,
               alpha = 0.05, global = TRUE, n_cl = 1, verbose = TRUE)
res_prim_AC_phylum = out_AC$res
```

2nd analysis (with ANCOMBC2 pairwise function):
```
output = ancombc2(data = tse_abc, assay_name = "counts",
              tax_level = "Phylum",
              fix_formula = "group",
              p_adj_method = "holm", prv_cut = 0.10, lib_cut = 1000,
              group = "group", struc_zero = TRUE, neg_lb = TRUE,
              global = TRUE, pairwise = TRUE,
              alpha = 0.05, n_cl = 1, verbose = TRUE)

res_pair = output$res_pair
```

**Comment by FrederickHuangLin** [comment]
Hi @ChihYingLu,

Thanks for your inquiry!

The reason why you saw much more conservative results of `ancombc2` pairwise test is because it implements the mixed directional false discover rate (mdFDR). 

I copied the following from the `ancombc2` vignette for your reference:

> The ANCOM-BC2 methodology extends ANCOM-BC for multiple groups and repeated measurements as follows:

> Multiple pairwise directional test: When performning pairwise directional test, the mixed directional false discover rate (mdFDR) should be taken into account. The mdFDR is the combination of false discovery rate due to multiple testing, multiple pairwise comparisons, and directional tests within each pairwise comparison. For example, suppose we have five taxa and three experimental groups: g1, g2, and g3. Thus, we are performing five tests corresponding to five taxa. For each taxon, we are also conducting three pairwise comparisons (g1 vs. g2, g2 vs. g3, and g1 vs. g3). Within each pairwise comparison, we wish to determine if the abundance has increased or decreased or did not change (direction of the effect size). Errors could occur in each step. The overall false discovery rate is controlled by the mdFDR methodology we adopted from (Guo, Sarkar, and Peddada 2010; Grandhi, Guo, and Peddada 2016).

Therefore, a more conservative result from `ancombc2` pairwise test is expected. If there is a concern of power, you can try using `p_adj_method = "BH"` instead.

Hope it helps!

Best,
Huang

**Comment by ChihYingLu** [comment]
@FrederickHuangLin thank you for your answer! now I can understand why.
Although I still got the same p and q values after trying p_adj_method = "BH".
I also realized that my sample size might be too small (n for the A, B, and C groups are 8, 6, 8) and has therefore reduced the analysis power.
I am curious how the modification of ANCOM-BC2 will affect its FDR and Power with small sample size data (n=5/group) compared to ANCOM-BC and other methods.

Best,
ChihYing

**Comment by FrederickHuangLin** [comment]
Hi @ChihYingLu,

Based on our simulation benchmark, the small sample size could be the bottleneck of power for almost all methods. Given the small sample size, I would suggest using raw p-values rather than adjusted p-values in your report, but also indicating that these results are exploratory and more for hypothesis generation.

Best,
Huang

**Comment by ChihYingLu** [comment]
Got it! Thank you very much for the suggestion.
