### ISSUE TITLE
Error in subsetting atlas dataset (from tutorial)

### ISSUE THREAD

**Issue by ManuelAOS** [FrederickHuangLin/ANCOMBC#144]
Hi!

I am trying to follow ANCOMBC tutorial at https://bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC.html

However I got stacked in the beginning, since I was not able to subset the atlas file.

The code is the following:

data(atlas1006)
tse = atlas1006[, atlas1006$time == 0]

And it generates the following Error message:

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'j' in selecting a method for function '[': $ operator not defined for this S4 class

Thanks in advance!

**Comment by antagomir** [comment]
There are two possible source for this error. There are both phyloseq and TreeSummarizedExperiment versions of this data in different packages. Moreover, the data set name has been updated in the miaTime package.

This should work:

```
library(miaTime)
data(hitchip1006)
tse0 <- hitchip1006 
tse <- tse0[, tse0$time == 0]
```

The examples should be updated, changing the data set name.

**Comment by FrederickHuangLin** [comment]
Thanks @ManuelAOS for your inquiry, and thanks @antagomir for your answer!

Your pull request has been approved! @antagomir

I will update and push a new version of `ANCOMBC` later this month.

Best,
Huang
