### ISSUE TITLE
SECOM

### ISSUE THREAD

**Issue by Alexlmy** [FrederickHuangLin/ANCOMBC#146]
### Discussed in https://github.com/FrederickHuangLin/ANCOMBC/discussions/145

<div type='discussions-op-text'>

<sup>Originally posted by **Alexlmy** February 11, 2023</sup>
library(ANCOMBC)
data(dietswap) 

## subset to baseline
tse = dietswap[, dietswap$timepoint == 1]

set.seed(123)
res_linear = secom_linear(data = list(tse), assay_name = "counts",
                          tax_level = "Phylum", pseudo = 0,
                          prv_cut = 0.5, lib_cut = 1000, corr_cut = 0.5,
                          wins_quant = c(0.05, 0.95), method = "pearson",
                          soft = FALSE, thresh_len = 20, n_cv = 10,
                          thresh_hard = 0.3, max_p = 0.005, n_cl = 2)

corr_th = res_linear$corr_th
corr_fl = res_linear$corr_fl

Thanks for developing the SECOM. Could you please help troubleshooting on the above example data?
(1) For "# subset to baseline": the code does not work as dietswap is a phyloseq, so I used the code below:
subset_samples (dietswap, timepoint == 1)
(2) When running the "sect_linear" function, I got the following error:
Error in secom_linear(data = list(tse), assay_name = "counts", tax_level = "Phylum",  : 
  unused arguments (data = list(tse), assay_name = "counts", tax_level = "Phylum")

Any help would be much appreciated!

</div>

**Comment by antagomir** [comment]
The dietswap dataset is avaible in both _phyloseq_ and _TreeSummarizedExperiment_ containers.

```
# TreeSE is available from the 
# Bioconductor ExperimentHub package microbiomeDataSets:
# https://microbiome.github.io/microbiomeDataSets/
library(microbiomeDataSets)
tse <- dietswap()

# phyloseq
library(microbiome)
data(dietswap, package="microbiome")
ps <- dietswap
```

If you switch to using the TreeSE version does it help?

The examples should be updated..

**Comment by antagomir** [comment]
The examples should be updated; I noticed that the ANCOMBC package has its own version of this data set.

Maintenance might be easier if we can converge to one version of this. 

Options:

1) update the data sets dietswap in the ANCOMBC package

2) update the examples to refer to dietswap data set from its original source/s

I consider the option (2) preferable for long-term maintenance although both are possible.

**Comment by antagomir** [comment]
This related to PR #148 which concerns hitchip1006/atlas1006 data set.

**Comment by FrederickHuangLin** [comment]
Hi @Alexlmy, please try to use the `tse` object as @antagomir suggested.

Thanks, @antagomir, for your suggestions!

I will remove the datasets in `ANCOMBC` and refer to the original sources. The update will be done later this month. 

Best,
Huang

**Comment by antagomir** [comment]
Great! If there arise TreeSE-related issues where you need help just ping us.

**Comment by Alexlmy** [comment]
Hi @antagomir @FrederickHuangLin Thanks a lot! Option 2 works!
