### ISSUE TITLE
taxon column of ANCOMBC2 results at species level

### ISSUE THREAD

**Issue by hjsung13** [FrederickHuangLin/ANCOMBC#147]
Hi, 
I am performing re-analysis with the recently updated ancombc2 function . The form of results (res) is different from that of the ancombc function, so I am writing a new code. 
My question is, in the res tab of the ancombc2 result, there is 'taxon' column printed as a form of 'Species: '. At this time, it is difficult to clearly specify if the different genus have the same species name such as Lactobacillus salivarius and Streptococcus salivarius. Rather, in the previous results of ancombc function, the ASV code column was presented together, so there seemed to be no room for confusion. How about adding the specific ASV code column printed in the res tab of the ancombc2 result as before?
Or is there a workaround solution that can clearly designate specific species belongs to different genus in the ancombc2 result at this moment?
Thanks as always for making such a great analysis tool.
I look forward to hearing from you soon.

**Comment by FrederickHuangLin** [comment]
Hi @hjsung13,

Thanks for your inquiry!

I think if you import the `tse` object, the `taxon` column in `res` will give you the full taxonomic classifications for a taxon. Is it not the case from your end?

Best,
Huang

**Comment by hjsung13** [comment]
Thanks for your reply. 

In my case, i made my phyloseq object by using qiime2R package. 
After creating a phyloseq object, I solved the above problem by forcibly changing the name in the species rank of the taxonomic table to Genus + species name and inputting it to ANCOM-BC. By doing this, even if the species name is the same, it was possible to perform differential analysis at the species level clearly without confusion. In this way, it was possible to proceed without the error of the taxonomyRank ( ) function embedding in ancombc2 function.
Thank you for your concern.

Best regards,
Hjsung
