### ISSUE TITLE
how to catch normalization results

### ISSUE THREAD

**Issue by sghignone** [FrederickHuangLin/ANCOMBC#149]
Hi!
I apologize if the question has already been asked, perhaps in other terms...

The Authors states in their recent papers that "normalization method introduced in ANCOM-BC performs well", 
But so far, I wasn't able to find out how to apply this method on my feature_table ...this in order to update traditional normalization step, such as rarefaction or Standardization abundances to the median sequencing depth, in my workflows.
Any idea about ?
Thanks

PS. the final goal is to perform alpha and beta diversity analyses on normalized feature_table

**Comment by FrederickHuangLin** [comment]
Hi @sghignone,

You can find the corresponding information in the section of `Bias-corrected abundances` [here](https://www.bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC.html).

Best,
Huang
