### ISSUE TITLE
Error in ancombc

### ISSUE THREAD

**Issue by lakerwsl** [FrederickHuangLin/ANCOMBC#15]
Hi,

This package is very interesting. I tried it and found that it reported the error: "Error in eval(predvars, data, env) : 
  numeric 'envir' arg not of length one" when the data is sparse. I am wondering if you have any suggestions on it.

Shulei

**Comment by FrederickHuangLin** [comment]
Hi @lakerwsl,

Thanks for posting your question! In order for me to better dig into the problem, may you please share with your codes and a mock dataset (with all confidential information marked)?

Thank you,
Huang

**Comment by jakob-wirbel** [comment]
Hey hey 👋 
i ran into the same problem and i think i found the reason for the error 😄 

If you have a single metadata variable (basically, only the group label) **AND** you would remove samples with the minimum library size cutoff, [this part of the code](https://github.com/FrederickHuangLin/ANCOMBC/blob/b3a21656cd592796e8da3dc69d58a2b239a63fc7/R/data_prep.R#L36) will return the metadata as a vector, not as a data.frame:
```
# Discard samples with library size < lib_cut
lib_size = colSums(feature_table, na.rm = TRUE)
if(any(lib_size < lib_cut)){
   subj_del = which(lib_size < lib_cut)
   feature_table = feature_table[, - subj_del]
   meta_data = meta_data[- subj_del, ]
}
```
I think it could be fixed very quickly by changing the line to:
```
meta_data = meta_data[- subj_del, , drop=FALSE]
```

Cheers

**Comment by FrederickHuangLin** [comment]
Hi @jakob-wirbel,

Thank you very much for catching this! The package will be updated shortly to fix this BUG!

Best,
Huang
