### ISSUE TITLE
Multi-group comparisons

### ISSUE THREAD

**Issue by shiqiluo520** [FrederickHuangLin/ANCOMBC#151]
Hi Huang,

I am doing the four-group comparison using ANCOM-BC II. Is it possible that ANCOM-BC II can give me the taxa soledy abundant in each group as Lefse can achieve?  Here I attched a example figure.
![微信图片_20230227162039](https://user-images.githubusercontent.com/66830201/221604241-c1aecead-8d8d-4e67-8885-4c035d1dcc73.png)

My code:
```
DA = ancombc2(data = pseq, assay_name = "counts", tax_level = NULL,fix_formula = "Severity.Time.2", rand_formula = NULL,
                                  p_adj_method = "BH", prv_cut = 0, lib_cut = 0, 
                                  group = "Severity.Time.2", struc_zero = TRUE, neg_lb = FALSE,alpha = 0.05, n_cl = 2, verbose = TRUE,
                                  global = TRUE, 
                                  iter_control = list(tol = 1e-5, max_iter = 20, 
                                                      verbose = TRUE),
                                  em_control = list(tol = 1e-5, max_iter = 100))
```
In res, there are "lfc_(Intercept)", "lfc_groupB", "lfc_groupC", "lfc_groupD". Is lfc_(Intercept) lfc_groupA? If so, can I extract the positive value from these four sheets to make the figure?

Thank you for your help!

Bests,
Shiqi

**Comment by FrederickHuangLin** [comment]
Hi @shiqiluo520,

`lfc_groupB`, `lfc_groupC`, `lfc_groupD` are the log (natural log) fold-changes with respect to the reference group, which is group A in your case. Thus, they mean `LFC (group B - group A)`, `LFC (group C - group A)`, and `LFC (group C - group A)`, respectively. `lfc_(Intercept)` is for grand mean which is probably not a parameter of interest.

You can also create the similar plot using the bias-corrected abundances. Please see section "Bias-corrected abundances" in this [vignette](https://bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC.html).

Best,
Huang
