### ISSUE TITLE
Some taxa absent from primary results

### ISSUE THREAD

**Issue by Bike** [FrederickHuangLin/ANCOMBC#153]
Hello,

I'm betting this is a simple question, but I checked the documentation and I'm still confused. I have a dataset, `ps_final`, with 2,803 taxa. When I run the following code:

```r
ancomb_results <- ancombc2(ps_final, fix_formula = "diet + sex", p_adj_method="holm", tax_level="Genus",
                           group = "diet", prv_cut=0, struc_zero=TRUE, neg_lb = TRUE)

ancomb_results$feature_table
```

I notice that the number of taxa in the feature table has been pared down to 454. These 454 taxa also appear in the `ancomb_results$res` object. Initially, I assumed it was outputting only the differentially abundant taxa, but many taxa have p-values well above 0.05, so I'm not sure why they're being retained in the primary results. 

I think some statistical cutoff must be imposed somewhere, because if I instead switch the "group" argument in the code above from "diet" to "sex", I get a different number of taxa in the primary results object (388). This happens even when I keep all the other parameters constant (in other words, I keep `prv_cut` = `0`, `struc_zero` = `TRUE`, `neb_lb` = `TRUE`). 

Can you explain what determines which taxa appear in the results? (And why non-significant taxa appear?) Thanks a bunch!

**Comment by sinaeh10** [comment]
I'm having this issue as well, therefore following! It didn't happen before when I was using the old ancombc() function with the previous package version, but with ancombc2(), something is being imposed that filters away a number of taxa for the results. I'd like to also know what might be causing this!

**Comment by FrederickHuangLin** [comment]
Hi @Bike and @sinaeh10,

The reason why you saw the reduced number of taxa is that these taxa contained what we call structural zeros. You can find more details by checking the Details section (`?ancombc` or `?ancombc2`). 

> Such taxa are not further analyzed using ANCOM-BC, but the results are summarized in the overall summary

These taxa with structural zeros were declared significant based on the presence/absence test, not by ANCOM-BC or ANCOM-BC2 methodology. Thus, we decided to summarize them separately and not to include them in the ANCOM-BC or ANCOM-BC2 main results. You can access the results of the presence/absence test by checking `zero_ind`.

Best,
Huang
