### ISSUE TITLE
exact difference between "formula" and "group" parameters

### ISSUE THREAD

**Issue by Robvh-git** [FrederickHuangLin/ANCOMBC#154]
Hello,

as the title says: what is the exact difference between "formula" and "group" as parameters in the ```ancombc``` command? And how are they differently treated in the analysis? (if read the explanation of the parameters in the output of ```?ancombc```

As I now understand it, the for the "formula" parameter, you specify ALL variables of your experiment that can have an influence on the microbial abundances. For the "group" parameter, you specify only the variable of interest? Is this correct? However, the output also contains tests for all the "formula" variables.

Could you see the "formula" variables a bit as random effects? 

But should the variable you specify in the "group" parameter, also always  be included in the "formula" parameter?

Thanks!

**Comment by FrederickHuangLin** [comment]
Hi @Robvh-git,

Please find below my responses to your questions.

> As I now understand it, the for the "formula" parameter, you specify ALL variables of your experiment that can have an influence on the microbial abundances. For the "group" parameter, you specify only the variable of interest? Is this correct? However, the output also contains tests for all the "formula" variables.

For the `formula` argument, you are right. You should include ALL variables of your experiment that can have an influence on the microbial abundances. For the `group` variable, it is optional. You can activate it only when you are interested in detecting structural zeros or performing multi-group comparisons (global test in `ancombc`, and global test, pairwise directional test, Dunnett’s type of test, and trend test in `ancombc2`). For instance, if the variable of interest is a continuous variable, such as `age` (you might have some other categorical variables to adjust, but they are not your research interest), you can leave `group = NULL`. However, if the variable of interest is a categorical variable with more than three levels, and you are interested in performing multi-group comparisons, you then should specify it in both `formula` and `group` arguments, i.e., `formula = "group + other_adjusting_variables"` and `group = "group"`. The `formula` tells `ancombc` to do the bias-correction for the variables you specified and generate ANCOM-BC primary results (with no multi-group comparisons), and `group` tells it to make the multi-group comparisons. 

> Could you see the "formula" variables a bit as random effects?

No, `ancombc` does not support random effects. However, `ancombc2` can handle the mixed effects model. Free feel to test it out [ANCOM-BC2](https://www.bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC2.html)!

I think a lot of people have the same question. I will create a Q&A in this GitHub repository to clarify this issue. Thanks for your feedback, @Robvh-git !

Best,
Huang

**Comment by FrederickHuangLin** [comment]
For people who have a similar question, I just added the corresponding explanation to the [Commonly asked questions](https://github.com/FrederickHuangLin/ANCOMBC) section. Feel free to check it out.

Best,
Huang
