### ISSUE TITLE
meta_data not recognised in formulas

### ISSUE THREAD

**Issue by Cybernewbye** [FrederickHuangLin/ANCOMBC#157]
Dear Dr. Huang Lin

Many thanks for your great job and for the latest updates in ANCOMBC2. I sincerely find this tool the most comprehensive and versatile available for longitudinal compositional data.

I encounter the following error in both my files and running the tutorial found at
https://bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC2.html

Error in model.matrix.formula(formula(paste0("~", fix_formula)), data = meta_data) : 
  data must be a data.frame.
it's present in both phyloseq object inputs and  TreeSummarisedExperiment objects (of which I'm very unfamiliar with )

Thank you for your kind attention

Simone Becarelli

**Comment by madbullahi** [comment]
Dear CyberNewbye
Please could you point me to how you were able run the function ancombc2? Thank

**Comment by FrederickHuangLin** [comment]
Hi @Cybernewbye,

Could you provide a reproducible example code and inform me of the `ANCOMBC` version you are using?

Thanks,
Huang

**Comment by JackDettoLoco** [comment]
Hi, I'm a colleague of [Cybernewbye](https://github.com/Cybernewbye)

[EC_table.txt](https://github.com/FrederickHuangLin/ANCOMBC/files/11121195/EC_table.txt)
[Sample_data.txt](https://github.com/FrederickHuangLin/ANCOMBC/files/11121196/Sample_data.txt)

phy<-phyloseq(
  otu_table(read.delim(file = "EC_table.txt",header = T,row.names = 1,sep = " "),taxa_are_rows = T),
  sample_data(read.delim(file = "Sample_data.txt",header = T,row.names = 1,sep = "\t")))

out = ANCOMBC::ancombc2(data = phy, fix_formula = "Time", 
                       p_adj_method = "BH", prv_cut = 0.05, lib_cut = 0,
                       group = "Group", struc_zero = F, neg_lb = F, alpha = 0.05, global = T, dunnet = T)

These are the files and scripts that we are trying to run.

ancom version 2.0.2
r version 4.2.2
phyloseq version 1.38.0

Thx

**Comment by FrederickHuangLin** [comment]
Hi @Cybernewbye & @JackDettoLoco,

I was not able to reproduce the error message you encountered, but I did spot some potential issues. 

Given the datasets @JackDettoLoco provided, I first ran the following (note that the `group` variable **SHOULD** be included in the `fix_formula`):
```
library(microbiome)
library(ANCOMBC)
library(tidyverse)

otu_data = read.delim(file = "EC_table.txt", header = T, row.names = 1, sep = " ")
meta_data = read.delim(file = "Sample_data.txt",header = T,row.names = 1,sep = "\t")

phy = phyloseq(otu_table(otu_data, taxa_are_rows = T),
               sample_data(meta_data))

table(meta_data$Time)
table(meta_data$Group)
table(meta_data$Group2)

out = ANCOMBC::ancombc2(data = phy, fix_formula = "Group + Time",
                        p_adj_method = "BH", prv_cut = 0.05, lib_cut = 0,
                        group = "Group", struc_zero = F, neg_lb = F, alpha = 0.05, global = T, dunnet = T)
```
It gave me the error that:
```
Error: Estimation failed for the following covariates:
TimeT1
Consider removing these covariates
```

I did a quick linear regression on the data:
```
tmp_data = data.frame(y = as.numeric(otu_data[1, ]),
                      time = meta_data$Time,
                      group = meta_data$Group)
lm_fit = lm(y ~ time + group, data = tmp_data)
lm_fit
```
which showed that 
```
Call:
lm(formula = y ~ time + group, data = tmp_data)

Coefficients:
(Intercept)       timeT1  groupS1C4T1  groupS3C4T0  groupS3C4T1  groupS7C4T0  groupS7C4T1  groupS9C4T0  groupS9C4T1  
     180007      -113765       144198       -62577        80297       -15929        57388        54302           NA  
```

As you can see, some of the coefficients are NAs, indicating that the two variables `Time` and `Group` are highly correlated. Using `Group2` instead of `Group` solved the problem.
```
out = ANCOMBC::ancombc2(data = phy, fix_formula = "Group2 + Time",
                        p_adj_method = "BH", prv_cut = 0.05, lib_cut = 0,
                        group = "Group2", struc_zero = F, neg_lb = F, alpha = 0.05, global = T, dunnet = T)
```

Session info
```
R version 4.2.2 (2022-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.6.5

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] doRNG_1.8.3       rngtools_1.5.2    foreach_1.5.2     forcats_0.5.2     stringr_1.5.0     dplyr_1.0.10      purrr_1.0.0      
 [8] readr_2.1.3       tidyr_1.2.1       tibble_3.1.8      tidyverse_1.3.2   ANCOMBC_2.1.3     microbiome_1.20.0 ggplot2_3.4.0    
[15] phyloseq_1.42.0  
```

Best,
Huang
