### ISSUE TITLE
ancombc2 error: Error: 'rank' must be an non empty single character value.

### ISSUE THREAD

**Issue by jmartin77777** [FrederickHuangLin/ANCOMBC#165]
I'm trying to run a simple DA analysis looking at a single metadata attribute. I have count data per genome (UHGG v1.0 representative species) per sample in a 'features' file, with the genomes being the rows and the samples the columns. I also have a 2 column metadata file with the samples as the 1st column and the attribute being the 2nd. The attribute is a 2 state value, being HIGH or LOW (an independently calculated metric for each sample) and we want to figure out if any genomes are associated with that state. I also have a newick format tree file for the genomes as a 3rd input

I'm running this R script to try and format things and run the ancombc2() function on this data:
```
# Load required packages
if (!requireNamespace("devtools", quietly = TRUE))
  install.packages("devtools")
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
library(devtools)
install_github("FrederickHuangLin/ANCOMBC")
library(ANCOMBC)
library(ape)
library(SummarizedExperiment)

# CONTENTS OF Read_count_TEST.tsv FILE:
#
#   1	2	3	4	5
# GUT_GENOME095938	10999	18043	3179	9818	0
# GUT_GENOME143483	2383	3848	164282	7956	1704
# GUT_GENOME142525	0	274	757	21126	0
# GUT_GENOME143505	0	0	225085	0	34160
# GUT_GENOME239670	0	0	874	383	0
# GUT_GENOME096210	0	62270	21698	65972	928

# Load count table
counts <- read.table("Read_count_TEST.tsv", header = TRUE, row.names = 1, sep = "\t", check.names = FALSE)

# CONTENTS OF Comparison_TEST.tsv FILE:
#
# Sample_ID	Comparison
# 1	LOW
# 2	LOW
# 3	LOW
# 4	LOW
# 5	HIGH

# Load comparison metadata
metadata <- read.table("Comparison_TEST.tsv", header = TRUE, sep = "\t")

# Convert to SummarizedExperiment object
se <- SummarizedExperiment(assays = list(counts = as.matrix(counts)),
                           colData = metadata)

# CONTENTS OF NEWICK FORMAT TREE FILE tree.nwk
#
# (GUT_GENOME096210:0.06222438217,GUT_GENOME095938:0.2158654029,(((GUT_GENOME143483:0.03053768353,GUT_GENOME143505:0.09177198679):0.2028845613,GUT_GENOME239670:0.01857553888):0.3174187077,GUT_GENOME142525:0.3406307282):0.1383788269);

# Load tree file
tree <- read.tree("tree.nwk")

# Run ANCOM-BC2 analysis
ancombc2_res <- ancombc2(se, metadata$Comparison, tree)

# View results
View(ancombc2_res)
```

When the script tries to run the ancombc2() function its giving me this error:

"Error: 'rank' must be an non empty single character value."

I'm very new to using ANCOM-BC2 and naively was hoping that I was providing the minimum inputs needed. Can you help me get this barebones implementation working?

**Comment by FrederickHuangLin** [comment]
Hi @jmartin77777,

You have to use the named arguments. For instance, `ancombc2_res <- ancombc2(data = se, fix_formula = "Comparison")`. The `tree` object is not a required input for `ancombc2`. Please go to the [user manual](https://www.bioconductor.org/packages/release/bioc/manuals/ANCOMBC/man/ANCOMBC.pdf) or [vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC2.html) for details.

Best,
Huang

**Comment by jmartin77777** [comment]
I modified the R script to this:

```
# Load required packages
if (!requireNamespace("devtools", quietly = TRUE))
  install.packages("devtools")
library(devtools)
install_github("FrederickHuangLin/ANCOMBC")
library(ANCOMBC)
library(SummarizedExperiment)

# CONTENTS OF Read_count_TEST.tsv FILE:
#
#   1	2	3	4	5
# GUT_GENOME095938	10999	18043	3179	9818	0
# GUT_GENOME143483	2383	3848	164282	7956	1704
# GUT_GENOME142525	0	274	757	21126	0
# GUT_GENOME143505	0	0	225085	0	34160
# GUT_GENOME239670	0	0	874	383	0
# GUT_GENOME096210	0	62270	21698	65972	928

# Load count table
counts <- read.table("Read_count_TEST.tsv", header = TRUE, row.names = 1, sep = "\t", check.names = FALSE)

# CONTENTS OF Comparison_TEST.tsv FILE:
#
# Sample_ID	Comparison
# 1	LOW
# 2	LOW
# 3	LOW
# 4	LOW
# 5	HIGH

# Load comparison metadata
metadata <- read.table("Comparison_TEST.tsv", header = TRUE, sep = "\t")

# Convert to SummarizedExperiment object
se <- SummarizedExperiment(assays = list(counts = as.matrix(counts)), colData = metadata)

# Run ANCOM-BC2 analysis
ancombc2_res <- ancombc2(data = se, fix_formula = "Comparison")

# View results
View(ancombc2_res)
```

And its now giving this error message:

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘altExp<-’ for signature ‘"SummarizedExperiment", "character"’

Is there something else I'm missing? My entire input for my testing is what I show in comments within the code above if you want to reproduce the error.

**Comment by FrederickHuangLin** [comment]
Hi @jmartin77777,

Could you create a `tse` object instead of the `se` object for the input data?
```
# Create the tse object
assays = S4Vectors::SimpleList(counts = as.matrix(counts))
smd = S4Vectors::DataFrame(metadata)
tse = TreeSummarizedExperiment::TreeSummarizedExperiment(assays = assays, colData = smd)
```
Let me know if it solves the problem.

Best,
Huang

**Comment by jmartin77777** [comment]
That worked! It completed on my tiny test set with no errors! Thank you so much!
