### ISSUE TITLE
Including or excluding unclassified reads from Kraken2/Bracken counts

### ISSUE THREAD

**Issue by hkaspersen** [FrederickHuangLin/ANCOMBC#170]
Hello, and thank you for an excellent package!

I am currently using ANCOM-BC for normalizing my data from Bracken, but I am unsure whether or not to include the unclassified reads. Bracken filter the unclassified reads from Kraken2 out, and I was wondering how this might affect the results from the normalization?
In my samples there is a very large fraction of unclassified reads (~50%) due to the nature of the samples (poultry caecal samples, probably not so represented in the Kraken2 database).

Do you have any suggestions regarding the unclassified reads?

**Comment by FrederickHuangLin** [comment]
Hi @hkaspersen,

Thank you for your inquiry!

Based on our simulation benchmark, the ANCOM-BC (or ANCOM-BC2) methodology is robust to unclassified reads. As long as you have a sufficiently large number of taxa (more than 100), the methodology can effectively perform the bias correction.

Best regards,
Huang
