### ISSUE TITLE
TreeSE support for non-taxonomic ranks

### ISSUE THREAD

**Issue by antagomir** [FrederickHuangLin/ANCOMBC#174]
The `tax_level` for TreeSE objects in `ancombc2` must be among `taxonomyRanks(tse)`. 

This excludes the use of OTUs or ASVs in `rowData(tse)`, for instance, for ancombc2.

Solution: allow to use also other rowData fields besides taxonomyRanks. 

We could prepare a PR for this.

**Comment by FrederickHuangLin** [comment]
Hi @antagomir,

Thank you for bringing up the issue regarding the `tax_level` parameter. 

Yes, please provide a PR to the `bugfix` branch if possible. Your efforts in improving the package are greatly appreciated.

Best regards,
Huang

**Comment by antagomir** [comment]
We are working on it.

Meanwhile I noticed one more point with this:

Calling:

`ANCOMBC::ancombc2(tse, "counts", tax_level="genus", "cohort+patient_status")`

can give error:
"Error: 'rank' must be a value from 'taxonomyRanks()'"

Now,`tax_level` is the parameter in _ancombc2_ function call but the error (from mia) mentions `rank` (although it refers to what is given in tax_level in ancombc2 call). This can be confusing for users. 

For tax_level checks, make the error message more informative.
