### ISSUE TITLE
How to interpret the fix_formula output when using two or more covariates

### ISSUE THREAD

**Issue by janettatop** [FrederickHuangLin/ANCOMBC#178]
In my data we have a time point group (baseline, control), when I use that in the fix_formula and group in the script, I obtain ± 20 differential abundant taxa in the primary analysis. In the previous ancom tool when you wanted to correct for another covariate you added one in fix_formula. So I also did that in fix_formula now in ancombc2, e.g. time_point + age_category (contains three variables). When I check the output I see three columns at the end with diff_time_pointControl, but also diff_age_category5_12 and diff_age_categoryabove_12, so only two of the three age variables.
 
When I follow your tutorial to plot the diff taxa I see that only de diff_timpointcontrol is plotted with a reduced number of taxa compared to timepoint only. My main questions are 1) is this indeed the correct way to determine diff taxa correcting for in this case age? And 2) how to interpret the diff_age taxa. Is this the output when you would analyse age_category and correct for time_point.

I would very much appreciate if you could make the time to clarify this.
Janetta

**Comment by FrederickHuangLin** [comment]
Hi Janetta,

The ANCOM-BC or ANCOM-BC2 methodology is essentially a linear regression model on bias-corrected log abundances. When you specify `fix_formula` in the `ancombc2` function, it is similar to specifying the predictor variable `x` in a linear regression model `y ~ x`. Therefore, the interpretation of the results is quite similar to that of a linear regression model. You can obtain log fold-changes (`lfc`) for each variable, standard errors, p-values, adjusted p-values, and information on whether the variable is significant or not (indicated by the `diff` columns where TRUE indicates significance).

Best regards,
Huang

**Comment by aimirza** [comment]
@FrederickHuangLin Just to be clear, if I wanted to adjust for covariables, i list them before the main variable like so?: `fix_formula = "covaraible1+ covaraible2 + covaraible3+ main_variable"`
