### ISSUE TITLE
"worker initialization failed: there is no package called ‘doRNG’"

### ISSUE THREAD

**Issue by amkilpatrick** [FrederickHuangLin/ANCOMBC#179]
Hello, I'm hoping you can help with an issue I'm having running `ancombc2()` on our HPC cluster. I'm attempting to run the following command:
```
#Run ANCOMBC
DE_d0= ancombc2(data= phyloseq_rna,
                tax_level = NULL,
                fix_formula= "gender", #final term is variable of interest
                pseudo= 1, #add a pseudocount of 1
                verbose=T,
                iter_control=list(tol = 0.01, max_iter = 20, verbose = T))
```
for `phyloseq_rna`, a 100 features x 30 sample object. This code runs (slowly) on my aging laptop (mac os), but fails on our (linux) HPC with the following message:
```
Obtaining initial estimates ...
ML iteration = 1, epsilon = 2.6
ML iteration = 2, epsilon = 2.3e-15
Estimating sample-specific biases ...
Error in e$fun(obj, substitute(ex), parent.frame(), e$data) : 
  worker initialization failed: there is no package called ‘doRNG’
Calls: ancombc2 -> %dorng% -> do.call -> <Anonymous> -> <Anonymous>
Execution halted
```
The sessionInfo confirms that doRNG is attached:
```
R version 4.2.2 (2022-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Scientific Linux 7.9 (Nitrogen)

Matrix products: default
BLAS:   /gpfs/igmmfs01/software/pkg/el7/apps/R/4.2.2/lib64/R/lib/libRblas.so
LAPACK: /gpfs/igmmfs01/software/pkg/el7/apps/R/4.2.2/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] doRNG_1.8.6     rngtools_1.5.2  foreach_1.5.2   ANCOMBC_2.0.2  
[5] phyloseq_1.42.0 edgeR_3.40.2    limma_3.54.2   

loaded via a namespace (and not attached):
  [1] readxl_1.4.2                   backports_1.4.1               
  [3] Hmisc_5.0-1                    plyr_1.8.8                    
  [5] igraph_1.4.0                   lazyeval_0.2.2   
...
```
Any thoughts as to what might be causing this error? It doesn't seem to be a problem of insufficient resources, as `qacct` shows only ~2G RAM used. I'd wondered if it might be something in the parallelisation code, which I've tried to avoid by explicitly specifying `n_cl=1` in the call, but I get the same result. Thanks in advance, happy to try any suggestions.

**Comment by FrederickHuangLin** [comment]
Hi @amkilpatrick,

I would recommend trying to run the same code locally on your computer to see if the error persists. If the code runs without any issues on your local machine, it is possible that there might be some specific configuration or compatibility issues with the cluster you are using.

In such cases, it is advisable to reach out to your cluster administrator or IT support team for assistance. They can provide you with more specific guidance and help troubleshoot any cluster-related issues you may be facing.

Best regards,
Huang
