### ISSUE TITLE
Error using ancombc2 and struc_zero = TRUE

### ISSUE THREAD

**Issue by AnnemarieVilladsen** [FrederickHuangLin/ANCOMBC#181]
Hi @FrederickHuangLin et al. 

Thanks for developing this updated ancombc2 package! However, I have an issue with the struc_zero argument.

When I run the following code, no error message occurs:
output_m_phylo_ba = ancombc2(data = phylo_m_2_baseline, 
                  assay_name = "counts", 
                  tax_level = "Family",
                  fix_formula = "Disease_group", 
                  rand_formula = NULL,
                  p_adj_method = "holm", 
                  pseudo = 0, pseudo_sens = TRUE,
                  prv_cut = 0.10, 
                  lib_cut = 0, s0_perc = 0.05,
                  group = NULL, 
                  struc_zero = FALSE, neg_lb = TRUE,
                  alpha = 0.05, n_cl = 1, 
                  verbose = FALSE,
                  global = FALSE, 
                  pairwise = FALSE, 
                  dunnet = FALSE, 
                  trend = FALSE)

BUT when changing struc_zero = TRUE I get the following error:

Error in !sameAsPreviousROW(y) : invalid argument type

Do you have any suggestions for this? 

I am new to microbiome analysis, so if any information is missing please let me know, and I will try my best to get you all information you may need. 

Thanks!

Best,
Annemarie

**Comment by FrederickHuangLin** [comment]
Hi @AnnemarieVilladsen,

Thank you for your question. In the ANCOM-BC2 methodology, specifying the `group` variable is required if you are interested in detecting structural zeros and performing multi-group comparisons such as the global test, pairwise directional test, Dunnett's type of test, and trend test.

If you want to detect structural zeros and perform these multi-group comparisons, you should set the `group` argument to a non-NULL value. This will allow you to analyze the data accordingly. For more detailed information and instructions, please refer to the user manual of the ANCOM-BC2 package.

Best regards,
Huang
