### ISSUE TITLE
Pattern analysis detected non-consistent patterns

### ISSUE THREAD

**Issue by GiBacci** [FrederickHuangLin/ANCOMBC#182]
I'm working on a big dataset containing more than 2'000 microbial species along an anthropic gradient with 4 levels called: P1, P2, I, and M. I ran pattern analysis by using two 3x3 contrast matrices constructed this way (`gradient` is the ordered factor described above):

```R
n <- nlevels(gradient) - 1
cntrs <- diag(rep(1, n))
cntrs[row(cntrs) == col(cntrs) + 1] <- -1
cntrs <- list(cntrs, cntrs * -1)
```
The content of `cntrs` is:

```
[[1]]
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]   -1    1    0
[3,]    0   -1    1

[[2]]
     [,1] [,2] [,3]
[1,]   -1    0    0
[2,]    1   -1    0
[3,]    0    1   -1
```
which should correspond to the gradient `[ P1 < P2 < I < M ]` and its inverse `[ P1 > P2 > I > M ]`.

Before launching ANCOMBC2, I have selected the top 100 species (detected from PCA) from my `phyloseq` object (called `exp`) to speed up the process:

```R
res.grad <- ancombc2(exp, assay_name = "otu_table", 
                     fix_formula = "gradient", 
                     group = "gradient",
                     verbose = TRUE,
                     pseudo_sens = TRUE,
                     trend = TRUE,
                     n_cl = 6,
                     trend_control = list(contrast = cntrs,
                                          node = as.list(rep(n, length(cntrs))),
                                          solver = "ECOS",
                                          B = 20))
```
Everything goes fine but, when I try to plot the gradient, I get non-consistent results:

![image](https://github.com/FrederickHuangLin/ANCOMBC/assets/3354163/5738c991-947e-4234-b87c-113d43edd047)

Some ASVs report a V-shaped pattern such as AVS10, 21, 75, 99 that are not compatible with the contrast matrices that I used to detect patterns across the gradient. Also, is there a way to detect which pattern corresponds to which contrast matrix? In other words, is there a way to detect significantly increasing / decreasing patterns?

Any help will be appreciated!

Thanks in advance,
Giovanni

**Comment by FrederickHuangLin** [comment]
Hi @GiBacci,

Thank you for your inquiry!

Regarding the figure generation, I recommend using the effect sizes estimated from the `res_trend` output for pattern analysis. These effect sizes reflect the correct constrained inference estimates. You can refer to section 4.9 in the [vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC2.html) for more details on how to interpret and use the effect sizes for pattern analysis.

I also wanted to mention that there has been a major update to `ancombc2`, which includes improvements in sensitivity analysis, as well as enhancements in power and computational efficiency. I encourage you to try out the new version (2.2.1) to take advantage of these updates.

We would also like to inform you that we have submitted a revised version of the ANCOM-BC2 paper, and we expect the preprint of the paper to be available in approximately 2 weeks.

If you have any further questions, please don't hesitate to ask.

Best regards,
Huang
