### ISSUE TITLE
Is there a way to test Paired-samples in ANCOMBC2?

### ISSUE THREAD

**Issue by kazubado33** [FrederickHuangLin/ANCOMBC#183]
Hi, @FrederickHuangLin et al.

Thanks for developing this updated ancombc2 package!

However, I have one question.
Is there any way to test Paired-samples with ANCOMBC2?

Best regards.

**Comment by FrederickHuangLin** [comment]
Hi @kazubado33,

Thank you for your inquiry.

I wanted to inform you that, currently, the `ANCOMBC` package does not support paired-samples analysis. However, you can work around this limitation by specifying the `rand_formula` and fitting mixed-effects models. Please note that this approach may affect the statistical power of the analysis.

Best regards,
Huang
