### ISSUE TITLE
Interpretation of res_pair in a longitudinal ANCOM-BC2 model

### ISSUE THREAD

**Issue by luisebe** [FrederickHuangLin/ANCOMBC#185]
Dear author, 

i have a dataset with 4 groups, each patient has a baseline and a follow-up fecal sampling. Thus, I implemented the ANCOM-BC2 model via `ancombc2` with "Timepoint + group" as fixed formula and "(1 | ID)" as random formula. I understand that the output `$res` shows me the longitudinal changes for each taxon with the parameters (for lfc_Timepoint, se_Timepoint, W_Timepoint, p_Timepoint and q_Timepoint). However, I am unsure as to how to interpret the lfc parameters the model returns for the group factors. Does this represent the difference in longitudinal changes between the groups? or the difference between the groups at the follow_up visit or are the taxa pooled? how can I interpret the `$res_paired` output in this context? 

Thank you in advance. 

Best, 
Luise

**Comment by FrederickHuangLin** [comment]
Hi Luise,

Thank you for your inquiry!

The ANCOM-BC and ANCOM-BC2 methodologies are essentially regression models that work on bias-corrected log abundances. Therefore, their interpretations are similar to those of regression models. In a model with both `Timepoint` and `group`, the `lfc_group` coefficients should be interpreted as the log fold-changes while **holding** the `Timepoint` constant, similar to interpreting coefficients in a linear regression model.

Regarding your second question, the `res_pair` output provides pairwise comparison results based on the `group` parameter you specified. If your `group` variable has three levels, such as `A`, `B`, and `C`, the primary results `res` will only show the comparisons `B - A` and `C - A`. However, the `res_pair` output will include the additional comparison `B - C` while controlling the mixed differential false discovery rate (FDR).

Best regards,
Huang
