### ISSUE TITLE
Troubleshooting - res empty

### ISSUE THREAD

**Issue by drvarkey** [FrederickHuangLin/ANCOMBC#187]
Dear Frederick,
Thank you for developing ANCOMBC. I'm a fairly new user and still learning it.
Recently, I have been trying to apply ANCOMBC2 to a dataset but have had a few issues. The most recent one being the code below runs fine but there are no results (as per part of the output shown below). 
I was wondering if you might be able to help me identify the cause. Please let me know if you need more information. I tried using the dietswap data and it runs perfectly fine.
Could it simply be that there are no differences in my data? I would assume these would still produce some output. 
Many thanks in advance.

My phyloseq object used to run ancombc2 with:
phyloseq-class experiment-level object
otu_table()   OTU Table:   [ 572 taxa and 24 samples]
sample_data() Sample Data: [ 24 samples by 4 sample variables ]
tax_table()   Taxonomy Table: [ 572 taxa by 6 taxonomic ranks ]

The code used:
xyzan = ancombc2(data = xyz.pssub, tax_level = "Genus", fix_formula = "Treatment", rand_formula = NULL, p_adj_method = "holm", prv_cut = 0.1, lib_cut = 10, s0_perc = 0.05, group = "Treatment", struc_zero = TRUE, neg_lb = TRUE, alpha = 0.05, n_cl = 2, verbose = FALSE, global = TRUE, pairwise = TRUE, dunnet = TRUE, trend = FALSE, iter_control = list(tol = 0.01, max_iter = 20, verbose = FALSE), em_control = list(tol = 1e-05, max_iter = 1),  lme_control = lme4::lmerControl(), mdfdr_control = list(fwer_ctrl_method = "holm", B = 20), trend_control = list(contrast = NULL, node = NULL, solver = "ECOS", B = 100))

Partial Output:
$delta_em
[1]  0.01176996 -0.04419938 -0.04349377 -0.01420955

$delta_wls
[1]  0.01580419 -0.03882747 -0.03095125 -0.01138370

$res

$res_global

$res_pair

$res_dunn

$res_trend
NULL

**Comment by FrederickHuangLin** [comment]
Hi @drvarkey,

Thanks for your feedback! Did you see any warning or error message when running your code?

Best,
Huang

**Comment by drvarkey** [comment]
Hi Huang,
Thanks so much for your response and apologies for the delay.

I just reran the code while trying to see if there were any error messages, and it worked! While the output is not empty as previously, I still don't get any differentially abundant taxa but this likely just reflects the dataset, and not how ANCOMBC was run. 

Thanks again for developing such a great tool!

Cheers
Dee
