### ISSUE TITLE
Issue with ANCOMBC (Zero variances issue)

### ISSUE THREAD

**Issue by ake123** [FrederickHuangLin/ANCOMBC#188]
Hello,
Thank you for developing ANCOMBC. I have been trying ANCOMBC2 to a dataset and it used to work before and stated to notice this error since last week. Are there changes that should be done to fix such errors?
```r
Error in `{
    {
      rngtools::RNGseed(.doRNG.stream)
    }
    {
      output = fun_list[[1]](beta = beta1[, i], var_hat = var_hat1[, i], tol = em_control$
        tol, max_iter = em_control$max_iter)
    }
  }`:
! task 1 failed - "Zero variances have been detected for the following taxa:
Actinomadura, Alkalimarinus, Bhargavaea, Cardiobacterium, Chitinispirillum, Chloroherpeton, Fenollaria, Halobacillus, Helcococcus, Kosakonia, Litoribacillus, Melghirimyces, Methylophaga, Microbulbifer, Planococcus, Saccharomonospora, Salimicrobium, Thioalkalispira
Please remove these taxa or select a more parsimonious model"
Backtrace:
 1. ANCOMBC::ancombc2(...)
 4. foreach (local) `<fn>`(...)
 5. e$fun(obj, substitute(ex), parent.frame(), e$data)
Execution halted
```

**Comment by mkariush** [comment]
Hi ake123,
I'm struggling with the same problem (see my issue #186).

**Comment by FrederickHuangLin** [comment]
Hello @ake123 and @mkariush,

ANCOM-BC2 software has been updated based on feedback from the reviewers. However, please be aware that as ANCOM-BC2 is currently under peer review, the software may not be entirely stable at this stage. We apologize for any inconvenience this may cause.

In this update, we have completely removed the pseudo-count addition to ANCOM-BC2, as it has been shown to increase false positives. As a result, ANCOM-BC2 will now default to using the complete data. Nevertheless, we will conduct a sensitivity analysis to assess the robustness of the method concerning the pseudo-count addition to zeros. More detailed information can be found in the introduction section of this [vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC2.html).

Given that ANCOM-BC2 now works on complete datasets by default, it is essential to consider the presence of numerous zeros in some taxa, as this may impact the estimation of variances. Here are some general steps that can help mitigate this issue:

1. Add a small pseudo-count (e.g., 0.01) to the data. This approach yields similar code behavior to the previous version, but it is generally not recommended based on our simulation benchmark.

2. Remove taxa with an extreme number of zeros. Specify the `group` variable and set `struc_zero = TRUE` to identify taxa with structural zeros and `ancombc2` will subsequently exclude them from the downstream analysis.

3. Increase the `prv_cut` parameter. For instance, you can set `prv_cut = 0.2` to remove sparse taxa.

We hope these steps prove useful for your analyses. Please feel free to provide feedback on your experience.

Best regards,
Huang
