### ISSUE TITLE
Different results after update

### ISSUE THREAD

**Issue by kamoors** [FrederickHuangLin/ANCOMBC#189]
Hi!

It appears that you have updated something within your package and my results are drastically different from before.. Different bordering strange! If I had a variable being significant in 15/150 taxa, now it's 148/150.. 

Is it written somewhere what exactly was done and what could cause this?

Kind regards,

Karl

**Comment by kamoors** [comment]
This is the code I used:
out = ancombc(phyloseq = dat,
              formula = "alcohol * PPI + Age + Gender + BMI + Food",
              p_adj_method = "fdr",
              zero_cut = 0.9,group = NULL)

**Comment by kamoors** [comment]
Also, I don't know if it is R, but I don't have the ancombc2 function in the package (1.4.0). I tried reinstalling it, closing/opening R.. Do you know what the problem might be?

**Comment by kamoors** [comment]
Ok, I think the problem was by outdated R version..

**Comment by shradhakhater** [comment]
Hi,
I have a similar issue as well. After ANCOMBC and R package update, I am getting many more taxa that are differentially abundant (significant). Currently I am using R version 4.3.1 and ANCOMBC version 2.2.1 and my code is:

 output = ancombc2(data = tse.mic, assay_name = "counts", tax_level = "Species",
                    fix_formula = "Obesity", rand_formula = NULL,
                    p_adj_method = "holm",                                                                      #pseudo was removed from ANCOMBC2 2.2.1
                    prv_cut = 0.10, lib_cut = 500, s0_perc = 0.05,
                    group = "CFS_simple", struc_zero = TRUE, neg_lb = TRUE,
                    alpha = 0.05, n_cl = 12, verbose = TRUE,
                    global = TRUE, pairwise = TRUE, dunnet = TRUE, trend = TRUE,
                    iter_control = list(tol = 1e-2, max_iter = 20, 
                                        verbose = TRUE),
                    em_control = list(tol = 1e-5, max_iter = 100),
                    lme_control = lme4::lmerControl(),
                    mdfdr_control = list(fwer_ctrl_method = "holm", B = 100),
                    trend_control = list(contrast = list(matrix(c(1, 0, -1, 1),
                                                                nrow = 2, 
                                                                byrow = TRUE),
                                                         matrix(c(-1, 0, 1, -1),
                                                                nrow = 2, 
                                                                byrow = TRUE)),
                                         node = list(2, 2),
                                         solver = "ECOS",
                                         B=100
                    ))

The code I was using with the earlier version of ANCOMBC (downloaded in May 2023) and R 4.3.0 was:

 output = ancombc2(data = tse.mic, assay_name = "counts", tax_level = "Genus",
                    fix_formula = "CFS_simple", rand_formula = NULL,
                    p_adj_method = "holm", pseudo = 0, pseudo_sens = TRUE, 
                    prv_cut = 0.10, lib_cut = 500, s0_perc = 0.05,
                    group = "CFS_simple", struc_zero = TRUE, neg_lb = TRUE,
                    alpha = 0.05, n_cl = 12, verbose = TRUE,
                    global = TRUE, pairwise = TRUE, dunnet = TRUE, trend = TRUE,
                    iter_control = list(tol = 1e-2, max_iter = 20, 
                                        verbose = TRUE),
                    em_control = list(tol = 1e-5, max_iter = 100),
                    lme_control = lme4::lmerControl(),
                    mdfdr_control = list(fwer_ctrl_method = "holm", B = 100),
                    trend_control = list(contrast = list(matrix(c(1, 0, -1, 1),
                                                                nrow = 2, 
                                                                byrow = TRUE),
                                                         matrix(c(-1, 0, 1, -1),
                                                                nrow = 2, 
                                                                byrow = TRUE)),
                                         node = list(2, 2),
                                         solver = "ECOS",
                                         B=100
                    ))
Can anyone help me with this problem?
Thanks

**Comment by FrederickHuangLin** [comment]
Hi @kamoors and @shradhakhater,

Thank you both for your valuable feedback!

I wanted to inform you that the ANCOM-BC2 software has undergone some updates based on the suggestions from the reviewers. However, it's essential to note that ANCOM-BC2 is currently under peer review, and as a result, the software may still have some stability issues at this stage. We anticipate the publication of the ANCOM-BC2 paper later this year. We apologize for any inconvenience this may cause.

In this update, we have made improvements to the variance formula in ANCOM-BC2, enhancing its power and ability to detect more significant taxa, as mentioned by @shradhakhater.

Additionally, we have completely removed the pseudo-count addition in ANCOM-BC2, as it has been shown to increase false positives. The default behavior now uses the complete data. Furthermore, we will conduct a sensitivity analysis to evaluate the robustness of the method concerning pseudo-count addition to zeros. More detailed information on these updates can be found in the introduction section of the [vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC2.html). It's worth noting that users are no longer required to manually pick a threshold for pseudo-count addition; the algorithm will automatically determine the robustness of the significance with respect to pseudo-count addition (`passed_ss.. = TRUE`) or not (`passed_ss.. = FALSE`).

If you have any further questions or concerns, please don't hesitate to reach out!

Best regards,
Huang

**Comment by joannakarolinapalka** [comment]
Hi! 
I also have issues with different results. And, more importantly, with random factor, which now does not seem to work.

My code is following:
output_species <- ancombc2(
  data = physeq_norar,
  assay_name = "counts", 
  tax_level = "Species", 
  fix_formula = "stage + CR_group + T", 
  rand_formula = "(1|vole_ID)",
  p_adj_method = "fdr", 
  lib_cut = 1000,
  prv_cut = 0.05,
  group = "T", 
  struc_zero = TRUE, 
  neg_lb = TRUE,
  alpha = 0.05, 
  global = TRUE 
)

Previously, the analysis looked ok, and now the standard error is the same for all samples, and nothing is significant (which is surprising at Species level). However, when the random formula is not included, the analysis is working flawlessly. 
How can I overcome this problem? Is there a possibility of using the old version of the package, or this issue will be fixed?

Greetings,
Joanna Palka

**Comment by FrederickHuangLin** [comment]
Hello Joanna @joannakarolinapalka,

I appreciate your feedback!

One of the significant changes in this update is that by default, `ancombc2` will not introduce a pseudo-count. To replicate the behavior of the previous version, you can manually add 1 to your data.

Regarding the issue with the random effects model, were you able to successfully execute the example longitudinal data found [here](https://bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC2.html)? Also, could you try aggregating your data to higher taxonomic levels (e.g., `tax_level = "Genus"`) and see what the results look like?

Best regards,
Huang

**Comment by joannakarolinapalka** [comment]
Hi Huang,

Thank you so much for your response. I was able to generate the same results as previously. 
Regarding your question - yes, I could run the code for the example longitudinal data without any problems. 

Greetings,
Joanna
