### ISSUE TITLE
tax_level: need help interpreting results

### ISSUE THREAD

**Issue by melissaszy** [FrederickHuangLin/ANCOMBC#190]
Hello,

I used ancombc2 function and specified that I want my data to be analysed at the genus level. my code is as such:
output = ancombc2(data = phyloseqobject, 
                  tax_level = "Genus",
                  fix_formula = "age+ cage")
res_prim = output$res

in res_prim, under "taxon" column, I have data such as:
Phylum:Proteobacteria
Class:Gammaproteobacteria
Genus:Bacillus
Genus:Enterococcus

my question is whether I am interpreting this correctly:
1. taxon that says "Genus:..." is exactly as I wanted, ie analysing my data at the genus level.
2. taxon that says "Phylum:..." or "Class:..." refers to a genus in that phylum or class that was not classified to the genus level. In other words, I can interprete "Phylum:Proteobacteria" as an unclassified genus from the phylum Proteobacteria.

Please let me know if I am correct/ wrong.

Cheers,
Melissa

**Comment by FrederickHuangLin** [comment]
Hello @melissaszy,

You have indeed grasped the concept correctly!

However, I would like to remind you to exercise caution when using ANCOM-BC2, as it is based on a paper that has not yet been published. The manuscript supporting ANCOM-BC2 is currently undergoing peer review, and as a result, the existing software version may not be entirely stable. The expected publication date for ANCOM-BC2 is later this year. Nonetheless, you are welcome to explore and experiment with the new features of ANCOM-BC2.

Best regards,
Huang
