### ISSUE TITLE
extract longitudinal differential abundance for each subgroup

### ISSUE THREAD

**Issue by luisebe** [FrederickHuangLin/ANCOMBC#197]
Hi Frederick, 

I am sorry to bother you again. I have patients which were measured 2x (once at baseline, once after intervention) who were allocated into 4 different diet groups. When running the formula = "Timepoint + diets", is it possible to extract the longitudinal changes per each diet group (and not, like res_dunn, the pairwise comparisons against the reference diet while keeping the factor Time constant)? 

I am trying to "DIY" it by stratifying my data set into the 4 diet groups, extracting the crude p value and the lfc for each ANCOMBC2 run (in total 4x), combining it into a data frame and then applying p.adjust methods like "BH". Is there a better way than this? 

Thank you very much!

Best, 
Luise

**Comment by FrederickHuangLin** [comment]
Hello Luise,

Another approach you can consider is manually creating a `Time_diet` variable by combining the `Timepoint` and `diets` variables you already have. The effect size you're interested in can then be calculated as `Time_diet = end_dietGroupA` - `Time_diet = baseline_dietGroupA`.

Best regards,
Frederick

**Comment by luisebe** [comment]
Dear Frederick, 

thank you very much for this suggestion - I'll be sure to give it a try!

Best, 
Luise

**Comment by Cybernewbye** [comment]
so the formula to be applied would be " formula = Time_diet" and group also be = Time_diet, right?

**Comment by FrederickHuangLin** [comment]
That is correct! @Cybernewbye
