### ISSUE TITLE
Unable to reproduce log bias corrected absolute abundance in ANCOMBC2 (V2.2.1) manually

### ISSUE THREAD

**Issue by GaryZhangYue** [FrederickHuangLin/ANCOMBC#198]
Hi Frederick,

I have a question regarding the calculation of log bias corrected absolute abundance in ANCOMBC2 (V2.2.1). In brief, I noticed that ANCOMBC2 now provides the  log bias corrected absolute abundance in the output, and users no longer need to calculate it manually. However, I compared the results between the output from ANCOMBC2, and the one I manually calculated using sample_frac and feature table following the procedure provided in ANCOMBC tutorial (see below), the results are drastically different: 

procedure I followed (pu.d.ac is the ancombc2 output); 

  samp_frac = pu.d.ac$samp_frac
   Replace NA with 0
  samp_frac[is.na(samp_frac)] = 0 
   Add pesudo-count (1) to avoid taking the log of 0
  log_obs_abn = log(pu.d.ac$feature_table + 1)
   Adjust the log observed abundances
  log_corr_abn = t(t(log_obs_abn) - samp_frac)

the first few line of the results:

> head(log_corr_abn,n = 3)
                        CTRL.S1   CTRL.S10   CTRL.S17    CTRL.S2   TC1.S22  TC1.S23
Kingdom:Unassigned   5.77191671  4.7892280 5.77809004  7.6267432 3.3792562 6.223468
Kingdom:d__Eukaryota 0.04506896 -0.2012046 2.46555829 -0.1134863 0.1211597 0.100975
Genus:Opalinata      2.12451050 -0.2012046 0.06766302 -0.1134863 0.1211597 0.100975
                         TC1.S31    TC1.S38
Kingdom:Unassigned    5.29922484  4.8374122
Kingdom:d__Eukaryota -0.08984689 -0.1324011
Genus:Opalinata      -0.08984689 -0.1324011

the first few line of ancombc2 bias_correct_log_table:

> head(pu.d.ac$bias_correct_log_table, n = 3)
                        CTRL.S1   CTRL.S10   CTRL.S17  CTRL.S2   TC1.S22   TC1.S23
Kingdom:Unassigned   0.28857789 -0.6976741 0.29469711 2.146232 -2.140041 0.7411962
Kingdom:d__Eukaryota         NA         NA 0.06766302       NA        NA        NA
Genus:Opalinata      0.04506896         NA         NA       NA        NA        NA
                       TC1.S31    TC1.S38
Kingdom:Unassigned   -0.185428 -0.6496327
Kingdom:d__Eukaryota        NA         NA
Genus:Opalinata             NA         NA

As shown, the results are drastically different. Adding pseudo-count 1 is unlikely the reason. Am I missing something here?

Here is the corresponding feature table and sample frac:

> head(pu.d.ac$feature_table, n = 3)
                     CTRL.S1 CTRL.S10 CTRL.S17 CTRL.S2 TC1.S22 TC1.S23 TC1.S31 TC1.S38
Kingdom:Unassigned       306      146      301    2298      25     455     218     143
Kingdom:d__Eukaryota       0        0       10       0       0       0       0       0
Genus:Opalinata            7        0        0       0       0       0       0       0
> pu.d.ac$samp_frac
    CTRL.S1    CTRL.S10    CTRL.S17     CTRL.S2     TC1.S22     TC1.S23     TC1.S31 
-0.04506896  0.20120458 -0.06766302  0.11348632 -0.12115971 -0.10097499  0.08984689 
    TC1.S38 
 0.13240112

Thank you for your help!

Best,
Gary Zhang

**Comment by FrederickHuangLin** [comment]
Hi Gary,

Thank you for your question!

I wanted to inform you that the ANCOM-BC2 software has undergone some updates based on the suggestions from the reviewers. However, it's essential to note that ANCOM-BC2 is currently under peer review, and as a result, the software may still have some stability issues at this stage. We anticipate the publication of the ANCOM-BC2 paper later this year. We apologize for any inconvenience this may cause.

In this update, we have made improvements to the variance formula in ANCOM-BC2, enhancing its power and ability to detect more significant taxa.

Additionally, we have completely removed the pseudo-count addition in ANCOM-BC2, as it has been shown to increase false positives. The default behavior now uses the complete data. Furthermore, we will conduct a sensitivity analysis to evaluate the robustness of the method concerning pseudo-count addition to zeros. More detailed information on these updates can be found in the introduction section of the [vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC2.html). It's worth noting that users are no longer required to manually pick a threshold for pseudo-count addition; the algorithm will automatically determine the robustness of the significance with respect to pseudo-count addition (passed_ss.. = TRUE) or not (passed_ss.. = FALSE).

Regarding your question about the changes in log bias-corrected absolute abundance, there are two key differences after the update of ancombc2:

+ Pseudo-count is no longer added, and taxa with zero abundances will be shown as NAs.

+ The log absolute abundance has been centered across each taxon, providing representations without taxon-specific biases.

If you have any further questions or concerns, please don't hesitate to reach out!

Best regards,
Huang

**Comment by GaryZhangYue** [comment]
Hi Huang,

Thank you so much for your clarification! Much appreciated! Looking forward to seeing ANCOM-BC2 being published!

Best,
Gary
