### ISSUE TITLE
inconsistent data structures

### ISSUE THREAD

**Issue by Midnighter** [FrederickHuangLin/ANCOMBC#20]
For my convenience, I transform parts of the result structure into one data frame. I noticed that when using one independent variable with two levels in the formula, the results for `$res$diff_abn`, `$res$p_val`, and `$res$q_val` can either be a simple vector when the parameter `struc_zero = FALSE` or they are a matrix with one column when `struc_zero = TRUE`. To me it makes most sense that they are always a matrix since this is the case when more than two levels are involved anyway. Either way, I believe that the outcome should be consistent independent of the `struc_zero` parameter.

**Comment by FrederickHuangLin** [comment]
Hi @Midnighter,

Thanks for your suggestion! I have checked that, as for version 1.0.4, `res$p_val` and `res$q_val` are both `data.frame`, but I did see inconsistent formats for `res$diff_abn` with different values of `struc_zero`. I will push a new version of ANCOMBC soon to address this issue. The latest version (1.0.5) will be available by this Friday. Please let me know how it looks like then :)

Best,
Huang
