### ISSUE TITLE
Fatal error when rand_formula not NULL

### ISSUE THREAD

**Issue by mladen5000** [FrederickHuangLin/ANCOMBC#205]
After most recent update - reproduced with dietswap longitudinal dataset example

**Comment by FrederickHuangLin** [comment]
Thanks for your feedback, @mladen5000!

I suspect it might be a package compatibility issue between the `phyloseq` and `lme4` packages. Could you let me know which version of Bioconductor you are using?

Could you also try running the following code to see if it produces any errors:

```R
library(phyloseq)
library(lme4)
fm1 <- lme4::lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
```

This might help us narrow down the issue further.

Best,
Huang

**Comment by mladen5000** [comment]
The code segment also leads to a fatal error:
`library(phyloseq)
library(lme4)
fm1 <- lme4::lmer(Reaction ~ Days + (Days | Subject), sleepstudy)`


`> BiocManager::version()
[1] ‘3.17’`

**Comment by FrederickHuangLin** [comment]
Yes, I encountered that error on my machine as well. It appears to be a package compatibility issue between `phyloseq` and `lme4`. I've reached out to the developers of both packages for more information. So far, a fresh installation of `phyloseq` using the command `remotes::install_github("joey711/phyloseq", force = TRUE)` has resolved the issue for me. You can find more details in this [post](https://github.com/lme4/lme4/issues/743).

Please let me know if this solution works for you as well.

Best regards,
Huang

**Comment by mladen5000** [comment]
This solution worked for me. Thank you so much - I really appreciate it
