### ISSUE TITLE
Very different result between v2.20 and v2.21

### ISSUE THREAD

**Issue by Axolotl233** [FrederickHuangLin/ANCOMBC#208]
Hi Huang,

Thank you for developing the ANCOMBC package, now I noticed it has uploaded v2.21. However, I found very different results between these two versions.

In v2.20, 132 different taxons were identified (using qvalue<0.05 as threshold). but in v2.21, 123 different taxons were identified (using qvalue < 0.05 and TURE passed_ss as threshold), and only 45 taxons overlapped in the two results.  In these 45 taxons, very different lfc values were observed. Besides, only 18 taxons have the same lfc trend. 

the comparison file were uploaded in the appendix, please check.
my count_data is created with metaphlan4 from metagenome sequencing data and used the same code in two versions, my code is `ancombc2_out = ancombc2(data =  phyloseqin_count_used,  p_adj_method = "fdr",
                        fix_formula = "groups",group = "groups", tax_level = "Species",
                        prv_cut = 0.1, lib_cut = 100, struc_zero = T, neg_lb = F,
                        iter_control = list(tol = 1e-5, max_iter = 20, verbose=T),
                        em_control = list(tol = 1e-5, max_iter = 100), 
                        alpha = 0.05, global = F, verbose = T)`
What could cause this and which result has more fitness with true condition? it seems that v2.20 is more consistent with species relative abundance. 

Thank you,
Nemo

[comparison.csv](https://github.com/FrederickHuangLin/ANCOMBC/files/12675520/comparison.csv)

**Comment by FrederickHuangLin** [comment]
Hello @Axolotl233,

I apologize for the delay in my response. In regards to the discrepancies you've noticed in the results after the update, you may find this [post](https://github.com/FrederickHuangLin/ANCOMBC/issues/198) to be a helpful resource for further insight.

Please do not hesitate to reach out if you have any additional questions.

Best regards,
Huang
