### ISSUE TITLE
SECOM for correlation with continuous variables

### ISSUE THREAD

**Issue by otaviolovison** [FrederickHuangLin/ANCOMBC#214]
Hello!

I would like to know if there is a way to use SECOM to evaluate the correlation of the pairwise relationships variation with continuous variables. 

Thank you!

**Comment by FrederickHuangLin** [comment]
Hello @otaviolovison,

Thank you for your interest in SECOM. Regrettably, in its current state, SECOM is unable to identify correlations involving continuous variables. Nevertheless, I consider this as a potential avenue for improvement in future updates to SECOM.

Best regards,
Huang
