### ISSUE TITLE
Interpreting ANCOMBC2 results for a continuous variable

### ISSUE THREAD

**Issue by LLansing** [FrederickHuangLin/ANCOMBC#216]
Hello,

In the experiment I'm working with, I wish to see which taxa are correlated with the factor of time. I have 8 timepoints from which my samples are taken, and I do not want to treat them as a categorical variable, since I am interested in taxa that are differentially abundant across time rather than between particular timepoints.

**I've ran _ancombc2_ (and tested with _ancombc_ as well) while treating the time variable as continuous, but I've been unable to find in the ancombc documentation or paper how to interpret the results (log-fold change, q_val) for a continuous variable. Could you please help me understand?**

---
Additionally, I ask for your opinion on the following. The lfc values of the significant diff taxa are much lower than I would have expected, compared to the other non-_time_ factors which were included in the formula. You can see in the following volcano plot that there are many taxa with strong q_values but weak lfc.
![image](https://github.com/FrederickHuangLin/ANCOMBC/assets/35748909/32ae278f-09f2-4013-9325-f1830d4395ac)

Plotting the raw reads over time of the significantly different taxa reveals that a number of them are taxa which have non-zero counts at early timepoints but have 0 (or very low) counts at later timepoints. (note: in the image, only one dot appears for later timepoints on the x-axis, but this is several samples overlapping)
![image](https://github.com/FrederickHuangLin/ANCOMBC/assets/35748909/231630b2-0325-4e11-a751-e6061b04bb6f)
I would have expected a stronger lfc for such taxa, given the strong drop off in counts over time. Am I misguided in this assumption?

**Comment by FrederickHuangLin** [comment]
Hello @LLansing,

Interpreting log fold-change and q-values for continuous variables is quite similar to how it's done for categorical variables. However, for continuous variables, the effect sizes correspond to a "one unit increase" in the continuous variable.

The difference between the log fold-change and the results you observed using the raw data likely arises from the fact that ANCOM-BC2 operates on bias-corrected abundances and, by default, works on complete data (excluding zeros). The analysis of zero counts is evaluated in pseudo-count sensitivity analysis.

If you have any further questions, please feel free to reach out.

Best regards,
Huang
