### ISSUE TITLE
Error in { :    task 1 failed - "Zero variances have been detected for the following taxa:

### ISSUE THREAD

**Issue by diefuechsin** [FrederickHuangLin/ANCOMBC#224]
Hello!

I am using the function ancombc2 for the first time and for one group (containing 2 levels to compare), which I want to compare in the analysis, I got no output and the error;
"Error in { : 
  task 1 failed - "Zero variances have been detected for the following taxa:" <list of some taxa was given here>

The code I was using:
`ancombc2_out <- ancombc2(data = df,
                         assay.type = "counts",
                         fix_formula = "Biofilm_site",
                         p_adj_method = "BH",
                         prv_cut = 0.1,
                         group = "Biofilm_site",
                         struc_zero = TRUE,
                         neg_lb = TRUE)`

I just wanted to ask, if in this case the best case would be to exclude the listed taxa and try again?
I already read your answer in another issue, about setting prv_cut (which I did) and setting the group variable (which I did). Did I understand  correctly that using pseudocounts (like 0.01) would not be the best thing to do?

Thank you very much in advance!
Best regards

**Comment by adossantos1** [comment]
I got the same error. Simply setting the my reference group as the first level in the factor in my group variable removed the error, but I don't know if it's a sure fire fix

**Comment by FrederickHuangLin** [comment]
Hello @diefuechsin,

Thank you for your inquiry!

I would recommend removing the listed taxa. If you performed the analysis at the ASV/OTU level, it's highly probable that a substantial number of taxa are quite sparse. The current default behavior of `ancombc2` is to work with the complete data. While you do have the option to add pseudo-counts to address the zeros, it's important to note that there is some reservation about adding pseudo-counts. If you choose to use pseudo-counts, please ensure that you clarify this in your publication.

Best regards,
Huang

**Comment by diefuechsin** [comment]
Thank you very much for your reply!
Best regards

**Comment by Yunuuuu** [comment]
A tricks to fix this issue, capture the error message and remove the taxa automatically: 
```r
ancombc2 <- function(data, ...) {
    tryCatch(
        ANCOMBC::ancombc2(data = data, ...),
        error = function(cnd) {
            bad_taxa <- strsplit(conditionMessage(cnd), "\n")[[c(1L, 2L)]]
            bad_taxa <- .subset2(strsplit(bad_taxa, ", "), 1L)
            ANCOMBC::ancombc2(data = data[!rownames(data) %in% bad_taxa, ], ...)
        }
    )
}
```
