### ISSUE TITLE
question about taxa with structural zeros and non-structural zeros groups

### ISSUE THREAD

**Issue by ChihYingLu** [FrederickHuangLin/ANCOMBC#226]
Hi Huang,

Thank you for updating the tool!

I have a question while using the ANCOM-BC2. I am comparing the taxa differential abundance between four groups (A, B, C, and D). Many taxa were structural zeros in one group (group A) but not in the other three groups (groups B, C, D). If my understanding is correct, these taxa will not be included in the ANCOM-BC2 pairwise analysis since structural zeros exist. What should I do if I still want to compare the differential abundance of the taxa between the three groups that are not structural zeros (pairwise comparison between B, C, and D)? 

Thank you very much!

Best,
Chih-Ying

**Comment by FrederickHuangLin** [comment]
Hello @ChihYingLu,

That's an excellent question you've raised. You are correct; when a taxon is identified as having structural zeros, it is excluded from further analysis. We acknowledge that this may not be the ideal method for handling structural zeros, and we are actively exploring better solutions within the software to address such situations, like the one you've encountered. 

For the time being, I would recommend temporarily disabling the detection of structural zeros and combining the results from both approaches (with and without structural zero detection) to obtain a more comprehensive perspective.

Best regards,
Huang

**Comment by ChihYingLu** [comment]
Hi Huang,

Oh, I see. That's a good suggestion! Thanks for your reply!
I am looking forward to the upcoming version of ANCOMBC.

Best,
Chih-Ying
