### ISSUE TITLE
The older version does not work now

### ISSUE THREAD

**Issue by xianshu-li** [FrederickHuangLin/ANCOMBC#228]
I have the ANCOMBC R package with version "1.4.0", then I followed this tutorial: https://bioconductor.org/packages/devel/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC2.html,
but I can not run ancombc on the example.

It gives this error message: Error in ancombc(data = NULL, assay_name = NULL, tax_level = "Family",  : 
  unused arguments (data = NULL, assay_name = NULL, tax_level = "Family", prv_cut = 0.1, n_cl = 1, verbose = TRUE),

but I use exact codes as the tutorial.

**Comment by herncaro** [comment]
I have version 1.6.4 and am encountering similar issues running ancombc while running the exact script I used last year to identify differentially abundant taxa in my sample. Is there a way to re-run an analysis conducted using the older version of ancombc at this time? I am also using a phyloseq object, if that may be contributing to an error.

**Comment by FrederickHuangLin** [comment]
Hello @xianshu-li and @herncaro,

The error messages you are encountering are a result of differences in the arguments between version 1.x.x and 2.x.x of the software. To identify the correct arguments for your current version of ANCOMBC, you can run `?ancombc` in your R console to access the documentation.

Best regards,
Huang
