### ISSUE TITLE
Applicability of structural zeros to continuous variables

### ISSUE THREAD

**Issue by jylee3247** [FrederickHuangLin/ANCOMBC#234]
Hi,

I'm currently analysing my microbiome data using `ANCOM-BC` in R.

Recently, I have been testing the association between continuous variables and taxonomic abundance using `ANCOM-BC`. 

My R code:
```r
ancombc(data = phyloseq,
        tax_level = "Genus",
        formula = "continuous_variable",
        group = NULL,
        struc_zero = TRUE,
        neg_lb = TRUE)
```

This might be a naive question, but I am wondering 
	1) if it's appropriate to use structural zeros when employing continuous variables
	2) and what is meaning of structural zeros for continuous variables.

It seems that structural zeros are only applicable to discrete variables, according to the `?ancombc` in R.

```
A taxon is considered to have structural zeros in some (>=1) groups if it is completely (or nearly completely) missing in these groups.
For instance, suppose there are three groups: g1, g2, and g3. 
If the counts of taxon A in g1 are 0 but nonzero in g2 and g3, then taxon A will be considered to contain structural zeros in g1.
```

I am aware that it is possible to conduct ANCOM-BC analysis using continuous variables like age as covariates. 
However, I am not sure if it is also acceptable to apply this method to continuous variables when they are not used as covariates."

Please let me know if there are anything that I have misunderstood.

Thank you for taking the time to read my question.

**Comment by FrederickHuangLin** [comment]
Hello @jylee3247,

Thank you for your inquiry.

Structural zeros, by definition, are typically associated with categorical variables. However, I do see potential in exploring the likelihood of "missing" data concerning the gradient of a continuous variable. Although I haven't had the opportunity to pursue this direction, I would recommend reaching out to the [author](https://www.niehs.nih.gov/research/atniehs/labs/bb/staff/peddada) who developed the concept of structural zeros for a more in-depth discussion on this matter.

Best regards,
Huang

**Comment by jylee3247** [comment]
Thank you for your response!

I will read related papers you recommended.

Thank you and Happy New Year :)
