### ISSUE TITLE
Error in `[.data.frame`(ss_flag, fix_eff) : undefined columns selected

### ISSUE THREAD

**Issue by Kris-Abdul** [FrederickHuangLin/ANCOMBC#242]
Hi, I'm new to Ancom-BC2 and I have been trying to run Ancombc2 on a tse that was coerced from a phyloseq object. I'm currently getting the following error and warning messages 
Error in `[.data.frame`(ss_flag, fix_eff) : undefined columns selected
In addition: Warning messages:
1: In for (i in seq_len(n)) { :
  closing unused connection 11 (<-L-2H2ZHH3:11615)
2: In for (i in seq_len(n)) { :
  closing unused connection 8 (<-L-2H2ZHH3:11615)
3: In sqrt(var_hat) : NaNs produced
4: In pt(abs(W), df = dof, lower.tail = FALSE) : NaNs produced

when I checked ss_flag and fix_eff both had values of NULL

Here is a copy of the code I am running 
anbc_test = ancombc2(data = bp7_tse, assay_name = "counts", tax_level = "Genus",
                  fix_formula = "Months_since_construction + description + Nitrite.as.N.Sol.mg.kg. + Total_HC_C9_C40.sum.mg.kg.",
                  rand_formula = NULL,
                  p_adj_method = "holm", pseudo_sens = TRUE,
                  prv_cut = 0.10, lib_cut = 1000, s0_perc = 0.05,
                  group = "description", struc_zero = FALSE, neg_lb = FALSE,
                  alpha = 0.05, n_cl = 2, verbose = TRUE,
                  global = FALSE, pairwise = TRUE, 
                  dunnet = FALSE, trend = FALSE,
                  iter_control = list(tol = 1e-5, max_iter = 20, 
                                      verbose = FALSE),
                  em_control = list(tol = 1e-5, max_iter = 100),
                  lme_control = NULL, 
                  mdfdr_control = list(fwer_ctrl_method = "holm", B = 100), 
                  trend_control = NULL)

I would greatly appreciate any help on this matter.

**Comment by Maggie8888** [comment]
Hi Kris, You should check if the variables you choose to be included as fixed effects have the exact same variable name as "Months_since_construction", "description", "Nitrite.as.N.Sol.mg.kg." and, "Total_HC_C9_C40.sum.mg.kg." in your data.
