### ISSUE TITLE
which group the differential features are enriched

### ISSUE THREAD

**Issue by yiluheihei** [FrederickHuangLin/ANCOMBC#25]
Hi Frederick,

Thanks for your great work.

In ANCOMBC, the global test is for testing whether there are some taxa that are differentially abundant in at least one group, and how can I determin which group the differential features are enriched. 

Assume there are three groups `A`, `B` anc `C`, `featureA` is differential among these three groups after running ANCOMBC, which group (A, B or C) the `featureA` is enriched in? Is the group which has largest mean abundance of `featureA`? If it is, how to got the absolute abundance, is the `Bias-adjusted abundances` of the result represents the
corrected absolute abudance?

I'm sorry If my question are too basic. Any help is much appreciated.

Thanks for your attention.

**Comment by FrederickHuangLin** [comment]
Hi @yiluheihei,

Thanks for your query!

Per your question, suppose three groups are `A`, `B`, and `C` and you detected `featureA` is differentially abundant in at least one group. In this case, group `A` will be the reference group. To see which group is enriched as compared to group `A`, you can check the coefficient (log fold change) from the primary results. See section 3.4.1 from the [vignette](https://bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC.html#ancombc-primary-result). For example, if the coefficients are `B - A = -0.1` and `C - A = 0.2`, apparently group `C` has enriched absolute abundances.

Hope it helps!
Huang

**Comment by yiluheihei** [comment]
Thanks for your kindly explanation.

After reading the [ANCOMBC paper](https://www.nature.com/articles/s41467-020-17041-7) and the R source code, I think there are two ways to identify which group the differential features are enriched.

1. As shown in your response,  using the coefficient (log fold change, `ancombc_out$res$beta`).
2. The mean abundances of the feature for all groups can be calculated based on the bias-adjust abundances (section 3.4.7 from the [vignette](https://bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC.html#bias-adjusted-abundances)), and the feature is enriched the group which has largest mean abundance.

Am I understanding this correctly?

Thanks again for your attention.

Best regards,
Yang

**Comment by FrederickHuangLin** [comment]
Yes, you are right! I just think using log fold change is more straightforward :)

Best,
Huang

**Comment by yiluheihei** [comment]
Thanks for your patience:smile:.

Best,
Yang
