### ISSUE TITLE
Failure to install ANCOMBC neither windows nor Ubuntu

### ISSUE THREAD

**Issue by emankhalaf** [FrederickHuangLin/ANCOMBC#261]
Hello,

I tried to install ANCOMBC in RStudio on Ubuntu 20.04 without success. Consequently, I tried installing it on Windows but encountered the same issue. By the way, I am using RStudio version 4.3.3 (Ubuntu), and  4.2.3 (windows)

See below from Ubuntu:
>BiocManager::install("ANCOMBC")
'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cloud.r-project.org/
Bioconductor version 3.17 (BiocManager 1.30.22), R 4.3.3 (2024-02-29)
Installing package(s) 'ANCOMBC'
also installing the dependencies ‘Cairo’, ‘ggrastr’, ‘scater’, ‘DirichletMultinomial’, ‘Rmpfr’, ‘gsl’, ‘mia’, ‘CVXR’, ‘energy’

trying URL 'https://cloud.r-project.org/src/contrib/Cairo_1.6-2.tar.gz'
Content type 'application/x-gzip' length 99417 bytes (97 KB)
==================================================
downloaded 97 KB

trying URL 'https://cloud.r-project.org/src/contrib/ggrastr_1.0.2.tar.gz'
Content type 'application/x-gzip' length 2592994 bytes (2.5 MB)
==================================================
downloaded 2.5 MB

trying URL 'https://bioconductor.org/packages/3.17/bioc/src/contrib/scater_1.28.0.tar.gz'
Content type 'application/gzip' length 4089325 bytes (3.9 MB)
==================================================
downloaded 3.9 MB

trying URL 'https://bioconductor.org/packages/3.17/bioc/src/contrib/DirichletMultinomial_1.42.0.tar.gz'
Content type 'application/gzip' length 438338 bytes (428 KB)
==================================================
downloaded 428 KB

trying URL 'https://cloud.r-project.org/src/contrib/Rmpfr_0.9-5.tar.gz'
Content type 'application/x-gzip' length 608053 bytes (593 KB)
==================================================
downloaded 593 KB

trying URL 'https://cloud.r-project.org/src/contrib/gsl_2.1-8.tar.gz'
Content type 'application/x-gzip' length 217997 bytes (212 KB)
==================================================
downloaded 212 KB

trying URL 'https://bioconductor.org/packages/3.17/bioc/src/contrib/mia_1.8.0.tar.gz'
Content type 'application/gzip' length 2117730 bytes (2.0 MB)
==================================================
downloaded 2.0 MB

trying URL 'https://cloud.r-project.org/src/contrib/CVXR_1.0-12.tar.gz'
Content type 'application/x-gzip' length 844245 bytes (824 KB)
==================================================
downloaded 824 KB

trying URL 'https://cloud.r-project.org/src/contrib/energy_1.7-11.tar.gz'
Content type 'application/x-gzip' length 57897 bytes (56 KB)
==================================================
downloaded 56 KB

trying URL 'https://bioconductor.org/packages/3.17/bioc/src/contrib/ANCOMBC_2.2.2.tar.gz'
Content type 'application/gzip' length 1068225 bytes (1.0 MB)
==================================================
downloaded 1.0 MB

* installing *source* package ‘Cairo’ ...
** package ‘Cairo’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking for sys/wait.h that is POSIX.1 compatible... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for string.h... (cached) yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for pkg-config... /usr/bin/pkg-config
checking whether pkg-config knows about cairo... no
configure: CAIRO_LIBS is unset, attempting to guess it.
configure: CAIRO_CFLAGS=
checking if R was compiled with the RConn patch... no
checking for cairo.h... no
configure: error: Cannot find cairo.h! Please install cairo (http://www.cairographics.org/) and/or set CAIRO_CFLAGS/LIBS correspondingly.
ERROR: configuration failed for package ‘Cairo’
* removing ‘/home/raizada/R/x86_64-pc-linux-gnu-library/4.3/Cairo’
* installing *source* package ‘DirichletMultinomial’ ...
** using staged installation
** libs
using C compiler: ‘gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0’
gcc -I"/usr/share/R/include" -DNDEBUG      `gsl-config --cflags` -DR_DIRICHLETMULTINOMIAL -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-CIJAF4/r-base-4.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c R_init_DirichletMultinomial.c -o R_init_DirichletMultinomial.o
/bin/bash: gsl-config: command not found
gcc -I"/usr/share/R/include" -DNDEBUG      `gsl-config --cflags` -DR_DIRICHLETMULTINOMIAL -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-CIJAF4/r-base-4.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c dirichlet_fit.c -o dirichlet_fit.o
/bin/bash: gsl-config: command not found
gcc -I"/usr/share/R/include" -DNDEBUG      `gsl-config --cflags` -DR_DIRICHLETMULTINOMIAL -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-CIJAF4/r-base-4.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c dirichlet_fit_main.c -o dirichlet_fit_main.o
/bin/bash: gsl-config: command not found
dirichlet_fit_main.c:1:10: fatal error: gsl/gsl_rng.h: No such file or directory
    1 | #include <gsl/gsl_rng.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [/usr/lib/R/etc/Makeconf:191: dirichlet_fit_main.o] Error 1
ERROR: compilation failed for package ‘DirichletMultinomial’
* removing ‘/home/raizada/R/x86_64-pc-linux-gnu-library/4.3/DirichletMultinomial’
* installing *source* package ‘Rmpfr’ ...
** package ‘Rmpfr’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking mpfr.h usability... no
checking mpfr.h presence... no
checking for mpfr.h... no
configure: error: Header file mpfr.h not found; maybe use --with-mpfr-include=INCLUDE_PATH
ERROR: configuration failed for package ‘Rmpfr’
* removing ‘/home/raizada/R/x86_64-pc-linux-gnu-library/4.3/Rmpfr’
* installing *source* package ‘gsl’ ...
** package ‘gsl’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking for gsl-config... no
configure: error: gsl-config not found, is GSL installed?
ERROR: configuration failed for package ‘gsl’
* removing ‘/home/raizada/R/x86_64-pc-linux-gnu-library/4.3/gsl’
ERROR: dependency ‘Cairo’ is not available for package ‘ggrastr’
* removing ‘/home/raizada/R/x86_64-pc-linux-gnu-library/4.3/ggrastr’
ERROR: dependency ‘Rmpfr’ is not available for package ‘CVXR’
* removing ‘/home/raizada/R/x86_64-pc-linux-gnu-library/4.3/CVXR’
ERROR: dependency ‘gsl’ is not available for package ‘energy’
* removing ‘/home/raizada/R/x86_64-pc-linux-gnu-library/4.3/energy’
ERROR: dependency ‘ggrastr’ is not available for package ‘scater’
* removing ‘/home/raizada/R/x86_64-pc-linux-gnu-library/4.3/scater’
ERROR: dependencies ‘scater’, ‘DirichletMultinomial’ are not available for package ‘mia’
* removing ‘/home/raizada/R/x86_64-pc-linux-gnu-library/4.3/mia’
ERROR: dependencies ‘mia’, ‘CVXR’, ‘energy’ are not available for package ‘ANCOMBC’
* removing ‘/home/raizada/R/x86_64-pc-linux-gnu-library/4.3/ANCOMBC’

The downloaded source packages are in
	‘/tmp/Rtmp7YRkII/downloaded_packages’
Installation paths not writeable, unable to update packages
  path: /usr/lib/R/library
  packages:
    codetools, lattice, MASS, nlme, spatial
Old packages: 'ape', 'bslib', 'callr', 'data.table', 'datawizard', 'dbplyr', 'dunn.test', 'effectsize', 'ggsci', 'gh', 'htmltools',
  'httpuv', 'httr2', 'insight', 'knitr', 'lme4', 'matrixStats', 'munsell', 'performance', 'pkgdown', 'promises', 'quanteda',
  'RcppArmadillo', 'reticulate', 'RSQLite', 'rstudioapi', 'sf', 'shiny', 'testthat', 'uwot', 'xfun'
Update all/some/none? [a/s/n]: 
Update all/some/none? [a/s/n]: 
n
Warning messages:
1: In install.packages(...) :
  installation of package ‘Cairo’ had non-zero exit status
2: In install.packages(...) :
  installation of package ‘DirichletMultinomial’ had non-zero exit status
3: In install.packages(...) :
  installation of package ‘Rmpfr’ had non-zero exit status
4: In install.packages(...) :
  installation of package ‘gsl’ had non-zero exit status
5: In install.packages(...) :
  installation of package ‘ggrastr’ had non-zero exit status
6: In install.packages(...) :
  installation of package ‘CVXR’ had non-zero exit status
7: In install.packages(...) :
  installation of package ‘energy’ had non-zero exit status
8: In install.packages(...) :
  installation of package ‘scater’ had non-zero exit status
9: In install.packages(...) :
  installation of package ‘mia’ had non-zero exit status
10: In install.packages(...) :
  installation of package ‘ANCOMBC’ had non-zero exit status

Help is much appreciated!

**Comment by cyklee** [comment]
> configure: error: Cannot find cairo.h! Please install cairo (http://www.cairographics.org/) and/or set CAIRO_CFLAGS/LIBS correspondingly.

Have you tried installing Cairo? You can install it on Ubuntu by running `sudo apt-get install libcairo2-dev` in the terminal.
