### ISSUE TITLE
"Error: subscript contains invalid names" when running ancombc2

### ISSUE THREAD

**Issue by tfccheng** [FrederickHuangLin/ANCOMBC#264]
When I ran ancombc2, it reported an error "Error: subscript contains invalid names".
I have tried both tse and transformed phyloseq object.
In my previous project, everything was ok. But this time, I don't know what went wrong.

output = ancombc2(data = tse, assay_name = "counts", tax_level = "Genus",
                    fix_formula = "Sample", rand_formula = NULL,
                    p_adj_method = "fdr", pseudo = 0, pseudo_sens = TRUE,
                    prv_cut = 0, lib_cut = 0, s0_perc = 0.05,
                    group = "Disease", struc_zero = TRUE, neg_lb = TRUE,
                    alpha = 0.2, n_cl = 12, verbose = TRUE,
                    global = TRUE, pairwise = TRUE, dunnet = TRUE, trend = TRUE,
                    iter_control = list(tol = 1e-2, max_iter = 20,
                                        verbose = TRUE),
                    em_control = list(tol = 1e-5, max_iter = 20),
                    lme_control = lme4::lmerControl(),
                    mdfdr_control = list(fwer_ctrl_method = "holm", B = 100),
                    trend_control = list(contrast = list(matrix(c(1, 0, -1, 1),
                                                                nrow = 2,
                                                                byrow = TRUE),
                                                         matrix(c(-1, 0, 1, -1),
                                                                nrow = 2,
                                                                byrow = TRUE)),
                                         node = list(2, 2),
                                         solver = "ECOS",
                                         B = 100))
![image](https://github.com/FrederickHuangLin/ANCOMBC/assets/56111768/de34be3b-2754-4aa5-9f93-fd27f0869e39)

**Comment by tfccheng** [comment]
I've found my issue. Please delete this issue topic. Thanks.

**Comment by mariamaseng** [comment]
I have the same problem! What was your issue tfccheng? :-)

**Comment by mariamaseng** [comment]
Hehe me to found it. I had called a fixed effect variable by wrong name.
