### ISSUE TITLE
Global test with multiple group variables

### ISSUE THREAD

**Issue by panc97** [FrederickHuangLin/ANCOMBC#27]
Hello Mr. Developer,

I'm now working on an analysis project. There are 3 major environmental factors (e.g. A, B and C) which we think would affect the abundance of microbiomes. In one step I'd like to test the association between the abundance of microbiomes and 2 of the factors (say B and C), but I am not sure how I could write my formula properly (sorry that this question is rather basic, my apologies). Could I perform a global test on both factors in this case? If so, I'm still wondering if ANCOM-BC support multiple group variables as input.

Any help would be much appreciated and thank you in advance!

Pan

**Comment by liuhh02** [comment]
From the tutorial [here](http://www.bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC.html) under _**3.3 Running ancombc function**_, the code snippet for the test is as follows:
`out = ancombc(phyloseq = phylum_data, formula = "age + nation + bmi_group", 
              p_adj_method = "holm", zero_cut = 0.90, lib_cut = 1000, 
              group = "nation", struc_zero = TRUE, neg_lb = TRUE, tol = 1e-5, 
              max_iter = 100, conserve = TRUE, alpha = 0.05, global = TRUE)`
I believe you can set your formula as "B + C".

**Comment by FrederickHuangLin** [comment]
Hi @panc97,

Thanks for your question regarding the global test. In your case, since in that specific step you are only interested in comparing B and C, you can create a subset of your data and use the two-group comparison function of `ancombc`.

A sample code for creating a subset of your data could be:
```
sub_data = data %>%
						filter(group %in% c("B", "C"))
```

Please let me know if you have any question!

Best,
Huang

**Comment by cmmertz** [comment]
Hi! I am also trying to determine differentially abundant ASVs in a group of interest that contains only two
categories. The Group is `Experiment` which can be either `E1` or `E2`. 

I am trying to set up ANCOMBC but am wondering if this is the correct input: 

out = ancombc(data = NULL, assay_name = NULL,
               tax_level = NULL, phyloseq = ps,
               formula = "Experiment",
               p_adj_method = "holm", prv_cut = 0.10, lib_cut = 1000,
               group = NULL, struc_zero = FALSE, neg_lb = FALSE, tol = 1e-5,
               max_iter = 100, conserve = FALSE, alpha = 0.05, global = NULL,
               n_cl = 1, verbose = TRUE)
res = out$res

Thank you!

**Comment by FrederickHuangLin** [comment]
> Hi! I am also trying to determine differentially abundant ASVs in a group of interest that contains only two categories. The Group is `Experiment` which can be either `E1` or `E2`.
> 
> I am trying to set up ANCOMBC but am wondering if this is the correct input:
> 
> out = ancombc(data = NULL, assay_name = NULL, tax_level = NULL, phyloseq = ps, formula = "Experiment", p_adj_method = "holm", prv_cut = 0.10, lib_cut = 1000, group = NULL, struc_zero = FALSE, neg_lb = FALSE, tol = 1e-5, max_iter = 100, conserve = FALSE, alpha = 0.05, global = NULL, n_cl = 1, verbose = TRUE) res = out$res
> 
> Thank you!

The specification seems fine to me. @cmmertz 

Best,
Huang
