### ISSUE TITLE
Warning: longer object length is not a multiple of shorter object length

### ISSUE THREAD

**Issue by xpolak37** [FrederickHuangLin/ANCOMBC#280]
While running ANCOMBC::ancombc2, I get 'Warning: longer object length is not a multiple of shorter object length'. Firstly, I ignored it, but the results are very different compared to other tools, so this could be the issue. I use the phyloseq object as the input so the input data should be OK, if not, the phyloseq would have displayed some warning or error.  Do you have any idea what could be causing this?

Thank you in advance!

Here is the code:
```
ANCOMBC::ancombc2(data = phyloseq_object,
                    fix_formula = "Group + Country", rand_formula = NULL,
                    p_adj_method = "BH", 
                    prv_cut = 0.0, lib_cut = 0, s0_perc = 0,
                    group = "Group",
                    alpha = 0.05, verbose = TRUE,
                    mdfdr_control = list(fwer_ctrl_method = "BH", B = 100))
```

**Comment by FrederickHuangLin** [comment]
Hi! Please refer to post #231 for detailed discussion. A patch has been pushed to the GitHub bugfix branch. We are working on a formal update now.

Best,
