### ISSUE TITLE
Issue with SECOM functions; Updates to DescTools::Winsorize

### ISSUE THREAD

**Issue by bpark67** [FrederickHuangLin/ANCOMBC#290]
I have noticed there is an issue with running the ```secom_linear``` and ```secom_dist``` functions due to an update to the ```DescTools::Winsorize``` function. It seems the ```Winsorize``` function was defined using different parameters.

For now, I am working around by downgrading the ```DescTools``` package to the 0.99.54 version.

**Comment by FrederickHuangLin** [comment]
Hi @bpark67,

We have corrected this issue in its devel version under "bug-fix" branch. The formal update will be released in the next few weeks.

Best,
