### ISSUE TITLE
package not available for R version 3.6.1?

### ISSUE THREAD

**Issue by pavlo888** [FrederickHuangLin/ANCOMBC#3]
Hi, 

I am trying to install ANCOMBC using the following command: 

`package ‘ANCOMBC’ is not available (for R version 3.6.1) 
`

But then I get the following result: 
`package ‘ANCOMBC’ is not available (for R version 3.6.1) 
`

Is there a way I could fix this? 

Cheers, 
Pablo

**Comment by FrederickHuangLin** [comment]
Hi Pablo,

Currently, the ANCOMBC package has been accepted on Bioconductor and added to its nightly builds.

To install the latest release version of ANCOMBC, you have to use the ‘bioc-devel’ version of *Bioconductor*.

For details, please see the updated README file or [here](https://bioconductor.org/developers/how-to/useDevel/).

Best,

Huang
