### ISSUE TITLE
More informative error message in 'Error in while (epsilon > tol & iterNum < max_iter) { : missing value where TRUE/FALSE needed'

### ISSUE THREAD

**Issue by sharvarinarendra** [FrederickHuangLin/ANCOMBC#31]
Hi @FrederickHuangLin ! 

I've been working with the ANCOM-BC package for the past couple of days and it's very intuitive and interesting. However, I would like to know more about this error message : 

```
'Error in while (epsilon > tol & iterNum < max_iter) { : missing value where TRUE/FALSE needed'
```

If perhaps you could add an enhancement in the package such that the user knows more details about why they are getting such an error, it would be useful. I have referred gone through your conversation in this issue : https://github.com/FrederickHuangLin/ANCOMBC/issues/16 , but it's still a little unclear, and may not be applicable in this case. Given that I am using the latest version of ANCOM-BC, could you provide me with more details about this error?

Thank you so much! Looking forward to hearing from you.

Best,
Sharvari Narendra

**Comment by FrederickHuangLin** [comment]
Thanks for your question and valuable suggesion, @sharvarinarendra! 

The error message basically means the embedded EM algorithm in `ancombc` does not converge, the most likely reason is the small number of taxa. May you give me a brief information of your data and how you implemented the `ancombc` function (the code you wrote)?

I will polish this error message in the next update. 

Best,
Huang
