### ISSUE TITLE
Support for (Tree)SummarizedExperiment

### ISSUE THREAD

**Issue by antagomir** [FrederickHuangLin/ANCOMBC#32]
ANCOMBC does currently support `phyloseq`. We are now actively working on an alternative framework - [miaverse](https://microbiome.github.io/) - based on the newer (Tree)SummarizedExperiment class, providing some enhanced capabilities. It would be relatively straightforward to add support for this class because they are closely related, phyloseq can always be converted to TSE [mia::makeTreeSummarizedExperimentFromphyloseq](https://microbiome.github.io/mia/reference/makePhyloseqFromTreeSummarizedExperiment.html) and TSE to phyloseq in many cases (not always as it is a superset). An example is shown in [Conversions between data formats in R](https://microbiome.github.io/OMA/data-introduction.html#loading-experimental-microbiome-data). 

Support for (Tree)SummarizedExperiment could be added  ancombc function (and possibly others?).

**Comment by FrederickHuangLin** [comment]
Hi @antagomir,

Thanks for your valuable suggestion and make me aware of the (Tree)SummarizedExperiment class. I will take a look at the webpages you provided and get back to you later.

Thank you,
Huang

**Comment by antagomir** [comment]
Great - the project is in beta, and not all documentation is up-to-date yet but should work. Extracting the abundance table and metadata from a TSE object is straightforward (one line each), after that there should be no difference to the handling as compared to phyloseq. This would allow linking ancombc directly to TSE-based workflows. We can provide support as needed.

**Comment by HenrikEckermann** [comment]
Hi @FrederickHuangLin and @antagomir,
I created a pull request for this: https://github.com/FrederickHuangLin/ANCOMBC/pulls

**Comment by antagomir** [comment]
Wow, nice! I hope this could be useful.

**Comment by FrederickHuangLin** [comment]
Hi @antagomir and @HenrikEckermann,

I am pleased to share with you that the major update for `ANCOMBC` package has been completed. Here are some highlighted new features:

- Add `ancombc2` function, which supports pairwise test and trend test for both cross-sectional and repeated measurements data
- Add sensitivity analysis for pseudo-count addition
- Fully support the `(Tree)SummarizedExperiment` class
- A more user-friendly output layout

I just pushed the changes to the Bioconductor branches. It might take a few business days for the package to become available (but the `devel` version is ready here!).

Additionally, it is highly appreciated if the [tutorial](https://microbiome.github.io/OMA/differential-abundance.html) of differential abundance analysis for `mia` could be updated accordingly. I am glad that `ANCOMBC` can be a part of `mia` pipeline!

Best,
Huang

**Comment by antagomir** [comment]
This is great! 

We should update mia tutorial, and consider updating [OMA](https://microbiome.github.io/OMA) (still in beta) as well! 

As soon as the time allows.

**Comment by antagomir** [comment]
I have opened [issue 316 in mia](https://github.com/microbiome/mia/issues/316).
