### ISSUE TITLE
Co-occurrence network with ANCOM-BC derived absolute abundances

### ISSUE THREAD

**Issue by zwallen** [FrederickHuangLin/ANCOMBC#35]
Hello,

We have performed differential abundance analysis using ANCOM-BC specifying the model "case_status + batch", where "case_status" is our variable of interest and denotes what samples came from a case or control individual, while "batch" is a covariate and denotes what sequencing batch a sample belonged to. 

We would now like to construct species to species co-occurrence networks of tested species. I would like to use estimated absolute abundances as input to the co-occurrence networks, but I'm unsure if this can be done, as I'm aware the estimated sampling fractions (and therefore the bias-adjusted abundances) are dependent on the model given to ANCOM-BC. In order to preserve any differences that would be present in absolute abundances of case vs control samples, would it make sense to just supply ANCOM-BC with the "batch" variable, compute estimated absolute abundances using the resulting sampling fractions, and use those abundances for input to network analysis (after any needed transformations or normalizations)?

Any info/suggestions is much appreciated!

**Comment by FrederickHuangLin** [comment]
Hi @zwallen,

Thanks for your interest in using ANCOMBC!

Just like any model-based inference, the correctly specification of the postulated model is critical to ANCOM-BC methodology, and the derived bias-adjusted abundances. Therefore, it is highly recommended that the model selection should not only be based on statistical significance, but also scientific justifications and related domain knowledge.

In your case, if you believe that the case_status is truly associated with taxa's abundances, it should be included in the model to obtain a more "precise" adjusted abundances. However, if the prior knowledge is limited, I would recommend including some sensitivity analyses (for example, 1) create the co-occurrence network using raw taxa abundances; 2) using the adjusted abundances with a more parsimonious ANCOM-BC model, etc.) in the supplementary material and see if a significant difference will be observed.

Best,
Huang
