### ISSUE TITLE
Error Message 

### ISSUE THREAD

**Issue by haleyhallowell** [FrederickHuangLin/ANCOMBC#36]
Hello! I am currently using ANCOMBC on a phyloseq object. When I run the function:

`G0Ancom = ANCOMBC::ancombc(phyloseq = pig0, formula = "Diet", p_adj_method = "holm", zero_cut = 0.90, group = "Diet",  struc_zero = TRUE, conserve = TRUE, neg_lb = FALSE, tol = 1e-5, max_iter = 100, alpha = 0.05)`

 I am getting this error: 

`Error in while (epsilon > tol & iterNum < max_iter) { : 
  missing value where TRUE/FALSE needed`

It seems that this issue has been brought up before, but i am not using a small amount of taxa (I have 48 OTUs). Any advice on how to remedy this? 

Thanks!

**Comment by FrederickHuangLin** [comment]
Hi @haleyhallowell,

Thanks for using ANCOMBC and posting the question here!

I am aware of this uninformative error message and will update it accordingly. Basically, it means the embedded E-M algorithm failed. One possible reason is the small sample size per group. I see your `group` variable is `Diet`, could you please let me know the sample size per group in your data?

Best,
Huang

**Comment by haleyhallowell** [comment]
Hey Huang, 

I believe that was an error in my part. Rather than using each individual sample within each group, I was averaging the samples together (stupidly lol). I entered each sample individually without averaging and I was able to get it to run no problem. Thanks so much for the information, and thank you for creating this package! Very much needed in the field. 

Cheers, 
Haley

**Comment by FrederickHuangLin** [comment]
I am glad your problem gots solved! So it is essentially due to the issue of small sample size (in your case, after averaging you only have one subject per group). I will add a new warning message regarding it. 

Again, thanks for using ANCOMBC!

Best,
Huang
