### ISSUE TITLE
Incorrect labelling of groups in output?

### ISSUE THREAD

**Issue by haleyhallowell** [FrederickHuangLin/ANCOMBC#39]
Hello! 

I have three treatment groups in the dataset I'm analyzing: Limit Fed, Ad Libitum, and High Fat. They are all listed as a "diet" variable, which i indicate in my code (see below). However, when I look at the output, I see the High Fat group listed twice with different numbers, and no Ad Libitum group. Am i inputing something incorrectly? I double checked my metadata and it seems correct. I have attached a sample out$res file for you to see. 

here is the line of code I run: 
`P0Ancom = ANCOMBC::ancombc(phyloseq = phylum_data0, formula = "Diet", p_adj_method = "holm", zero_cut = 0.90, group = "Diet", struc_zero = TRUE, conserve = TRUE, neg_lb = FALSE, tol = 1e-5, max_iter = 100, alpha = 0.05)`

`P0pval = P0Ancom$res`

[P0stats.csv](https://github.com/FrederickHuangLin/ANCOMBC/files/6926380/P0stats.csv)

Best, 
Haley

**Comment by FrederickHuangLin** [comment]
Hi,

I checked the attached file, it seems your `Diet` group has three levels: "High.Fat", "High.Fat." (be careful with the extra dot), and "Limit.Fed", but no "Ad Libitum" as you mentioned.

There is probably an coding error in your meta data. You can verify that by checking:
```
table(meta(phylum_data0))
```

Best,
Huang

**Comment by haleyhallowell** [comment]
Hello! I checked the metadata, and got this output: 
`table(meta(phylum_data0)[, "Diet"])

Ad_Libitum   High_Fat  Limit_Fed 
         2          2          2 `

I also went back and double checked the original metadata file itself and copy/pasted the diet treatments to make sure each were pair were identical. I uploaded the new metadata file and tried again, but am getting the same results as above.

**Comment by haleyhallowell** [comment]
Hello! Just checkin in to see if you have a remedy for this issue. Thanks!

**Comment by FrederickHuangLin** [comment]
My apologies for responding late, I was busy with the international relocation lately. I am afraid I might not be able to debug your issue using the metadata solely. May you please send both the microbiome data and metadata to my working Email: HUL40@pitt.edu, with all confidential information de-identified? I will look into this problem carefully.

Best,
Huang
