### ISSUE TITLE
Longitudinal analysis using ancombc

### ISSUE THREAD

**Issue by rusher321** [FrederickHuangLin/ANCOMBC#4]
Dear lin: 

About the analysis of the longitudinal data using ANCOM_BC;
I know that  ANCOM can be used to analyses longitudinal data;
Whether  ANCOM_BC would provide simialr function  ? 
or if we can use bias corrected data by ANCOM_BC to perform ANCOM ? 

Thanks for your great work  ~
best
huahui

**Comment by FrederickHuangLin** [comment]
Hi Huahui,

Thanks for your interest in using ANCOMBC!

Currently, the ANCOMBC package has been accepted on Bioconductor and added to its nightly builds. This version of ANCOMBC is able to perform covariates adjustment and global tests as mentioned in this paper.

The longitudinal analysis is currently not available, but we are drafting the paper about it. We will add the corresponding functions to the ANCOMBC package once the new paper gets published.

Stay tuned!

Huang

**Comment by rusher321** [comment]
Thanks for the reply and look forward to your great work  ~  
best
huahui
