### ISSUE TITLE
Global test results omit certain taxa

### ISSUE THREAD

**Issue by cednotsed** [FrederickHuangLin/ANCOMBC#40]
Hi,

I'm trying to identify taxa that are differentially abundant between different sequencing batches. I have two metadata columns, 'site' and 'kit'. My original otu_table has 663 samples and 3986 taxa. However, after running ANCOM-BC, the global test result table has only dimensions of 3834 x 6. Some taxa are not included in this result table. May I know why this may be the case? My command parameters are shown below.

column <- "kit"
out <- ancombc(phyloseq = phy_subset, formula = column,
                    p_adj_method = "BH", zero_cut = 1, lib_cut = 0,
                    group = column, struc_zero = FALSE, neg_lb = FALSE,
                    tol = 1e-5, max_iter = 1, conserve = F,
                    alpha = 0.05, global = TRUE)

Thanks in advance.

**Comment by FrederickHuangLin** [comment]
My apologies for responding late, I was relocating internationally lately.

Can you try setting `zero_cut = 1.1` and see if all taxa were kept? If you set `zero_cut = 1`, all-zero taxa will be discarded.

Huang
