### ISSUE TITLE
Help with out file

### ISSUE THREAD

**Issue by Tatisgua** [FrederickHuangLin/ANCOMBC#41]
First, Thank you for this tool!!
It is very impressive...

I do have a question, I am not that code smart, so I have a question/request help.

In the final output "out" all the tables has as rownames the taxa information. I wonder if it is possible to get that output with the tax_table rownames information and not the actual taxa info. Thanks.

**Comment by FrederickHuangLin** [comment]
Thanks for your inquiry.

I don't think the ANCOMBC package has that function. Actually, since the a phyloseq-class object was an argument in `ancombc` function, 
```
ancombc(
phyloseq,
formula,
p_adj_method = "holm",
zero_cut = 0.9,
lib_cut = 0,
group = NULL,
struc_zero = FALSE,
neg_lb = FALSE,
tol = 1e-05,
max_iter = 100,
conserve = FALSE,
alpha = 0.05,
global = FALSE
)
```
if you need the `tax_table` information, wouldn't it easier by checking `tax_table(phyloseq)`?

Huang
