### ISSUE TITLE
Confidence intervals from standard errors output by model?

### ISSUE THREAD

**Issue by pacificasommers** [FrederickHuangLin/ANCOMBC#44]
Hi, I'm really excited about this method and package! Thanks for developing it. 

I noticed in the original publication (https://doi.org/10.1038/s41467-020-17041-7) that log-fold changes were plotted with Bonferroni-corrected 95% confidence intervals (CIs) as the error bars, but the current release outputs standard errors (SEs) and not CIs directly. I haven't been able to find the documentation in the manuscript methods or in the vignette or package documentation for calculating CIs from the SEs - can a normal distribution be assumed to calculate those? 

Thanks for any help!

**Comment by FrederickHuangLin** [comment]
Yes, if you assume normality, the CI is simply the log fold-change +/- 1.96*SE. With Bonferroni correction, you can also change the number "1.96" accordingly.

Best,
Huang

**Comment by pacificasommers** [comment]
Thank you! I was not confident normality was a reasonable assumption here. It is good to hear that confirmation.

**Comment by FrederickHuangLin** [comment]
Yes, the normality assumption is not perfect especially when the number of zeros is large. However, when you have relatively complete data, in log scale (log fold-change), the normality assumption approximately holds.
