### ISSUE TITLE
Longitudinal analysis

### ISSUE THREAD

**Issue by dpelegri** [FrederickHuangLin/ANCOMBC#48]
Hi @FrederickHuangLin

I have seen the package and I find it very interesting. I have to do an analysis with longitudinal data and wanted to ask if there is any date for the new release containing longitudinal data analysis

Thanks in advance

Dolors Pelegrí

**Comment by FrederickHuangLin** [comment]
Hi @GTempl,

ANCOMBC currently is not able to handle longitudinal analysis, we are trying to extend the function by early next year.

Best,
Huang

**Comment by milanmlft** [comment]
Hi @FrederickHuangLin,

Any news about this? I would also be interested in applying ANCOMBC to longitudinal data.

Thanks in advance!

Best,
Milan

**Comment by FrederickHuangLin** [comment]
Hi @milanmlft,

I am pleased to share with you that the major update for `ANCOMBC` package has been completed. Here are some highlighted new features:

- Add `ancombc2` function, which supports pairwise test and trend test for both cross-sectional and repeated measurements data
- Add sensitivity analysis for pseudo-count addition
- Fully support the `(Tree)SummarizedExperiment` class
- A more user-friendly output layout

I just pushed the changes to the Bioconductor branches. It might take a few business days for the package to become available (but the `devel` version is ready here!).

Best,
Huang

**Comment by yan1365** [comment]
Hi @FrederickHuangLin,

May I ask is it possible for ANCOMBC2 to separate fixed effect from random effect? In other words, could it handle experimental design like randomize complete block design with two factors factorial treatment design?

Thanks

**Comment by FrederickHuangLin** [comment]
Hi @yan1365,

Not sure if I understand your question correctly, but in ANCOM-BC2, fixed effects are specified in `fix_formula` and random effects are specified in `rand_formula`. In that sense, they are separate. However, only estimates for fixed effects will be generated by ANCOM-BC2. No predictions for random effects will be returned.

Best,
Huang
