### ISSUE TITLE
Relation of W statistic and beta coefficient

### ISSUE THREAD

**Issue by rpelicae** [FrederickHuangLin/ANCOMBC#53]
Hi Huang,

I've been using your tool happily and I've read your paper (Lin & Peddada, 2020), the vignette, and the ANCOM-BC manual.

What is not entirely clear to me is how the effect size (beta coefficient of the log-linear model) relates to the ANOVA-like model proposed in Lin & Peddada, 2020. And how the significance of the effect is actually tested for.

Writing Eq(4) of Lin & Peddada, 2020 in log form, we have: log(Oijk) = log (cjk) + log(Θij) + eijk

From what I understand from the paper, this model could also be written in a log-linear form to explicitly account for the effect of a covariate: log(Oijk/cjk) = βi0 + βi1X + eijk

But the log-linear model equation is not written in the paper.

Then, for the W test statistic we have Eq(33) from the paper and the information in the manual: "W = beta/se" (standardized effect size).

So, how does W relates to the beta coefficient of the covariate X we're testing for ? How is the p-value of W computed ?

Kind regards,
Rudy

**Comment by FrederickHuangLin** [comment]
Hi Rudy,

That is a great question!

You are absolutely right, the log-linear model you found in the paper is equivalent to the model you have written down, which evolves other covariates `x`.  In our original paper, our focus was group comparisons. However, we were aware of the need for covariate adjustment, as well as pairwise group comparison, repeated measures, etc. So we believe the general log-linear model is more convenient and we will use these notations in the upcoming ANCOM-BC extension paper. The R user manual just took a step ahead :)

As shown in the user manual, `W` is the standardized log fold-change (`beta`), which is a Wald-type of statistic and the p-value is computed by assuming Nomarlity.

Best,
Huang

**Comment by rpelicae** [comment]
Dear Huang,

Thank you for your response, it is somewhat more clear to me now. Looking forward to the upcoming ANCOM-BC extension paper!

Good luck,
Rudy
