### ISSUE TITLE
Foldchange value vs logFoldchange

### ISSUE THREAD

**Issue by davidvilanova** [FrederickHuangLin/ANCOMBC#57]
Hi,
Is it correct to say that the log ratio between the tested conditions corresponds to the dataframe res$W=(beta/se)

In such case the Foldchange would be exp(1)^(abs(res$w) ?

So for example if res$w returns -1.363898358 than the FC will be exp(1)^(1.363898358) = **-3.91** ?

Is it correct ?

**Comment by FrederickHuangLin** [comment]
Hi @davidvilanova,

The log fold change corresponds to the `beta` value, not the `W` statistics, and you are right, the fold change can be obtained by exponentiating it.

Best,
Huang
