### ISSUE TITLE
error in evaluating the argument 'y' in selecting a method for function 'plot'

### ISSUE THREAD

**Issue by Nermin-Ghith** [FrederickHuangLin/ANCOMBC#69]
Hi,
I am running ANCOMBC to compare abundance levels between countries using the yes/no variable. I try to run the code to make a volcano plot but I get this error:
Error in h(simpleError(msg, call)) :  error in evaluating the argument 'y' in selecting a method for function 'plot': non-numeric argument to mathematical function. 
I have attached a photo of this issue with the R code. I wonder what is wrong here.

![image](https://user-images.githubusercontent.com/61286546/171949619-8f834b1f-1389-4c4c-9bef-98e6a1fddac4.png)

Best,
Nermin

**Comment by FrederickHuangLin** [comment]
Hi @Nermin-Ghith,

Could you print out `results.abc$beta$SDG_Index_Score_binary_num0` and `results.abc$q_val$SDG_Index_Score_binary_num0` and see what these numbers are?

Best,
Huang
