### ISSUE TITLE
Error in data_prep(..)

### ISSUE THREAD

**Issue by stan-iakhno** [FrederickHuangLin/ANCOMBC#7]
Hi Frederick,
Thanks for developing the methodology and the R package! 

When I run the toy example from ?help (GlobalPatterns) data, it runs with no problems. However, when I plug in my data, it givees me this error message:
```

Error in data_prep(phyloseq, group, zero_cut, lib_cut, global = global) : 
  The group variable should have >= 2 categories.
```

Any help is much appreciated!

Best. Stan

**Comment by FrederickHuangLin** [comment]
Hi @stan-iakhno,

The error message means the `group` variable you specified in the `ancombc` function contains less than 2 categories or levels. 

Suppose your metadata is called `meta_data` and the group variable is called `group`, you can check the number of levels it has by executing :

`length(unique(meta_data[, group]))`.

If it turns out to be less than 2, you can consider either using a different `group` variable or specifying `group = NULL` in the `ancombc` function.

Best,

Huang

**Comment by stan-iakhno** [comment]
Thanks for your reply @FrederickHuangLin ! I was trying to replicate the issue myself and got a different error.
```
Error in tapply(present_table[i, ], group_data, function(x) mean(x, na.rm = TRUE)) : 
  arguments must have same length
In addition: Warning message:
In data_prep(phyloseq, group, zero_cut, lib_cut, global = global) :
  The multi-group comparison will be deactivated as the group variable has < 3 categories.
```
What could go wrong here?

Here is the code I run:

[ps.zip](https://github.com/FrederickHuangLin/ANCOMBC/files/5434993/ps.zip)


```
library(dplyr)
library(nloptr)
library(ANCOMBC)

out = ancombc(phyloseq = ps, formula = "diet",
              p_adj_method = "holm", zero_cut = 0.90, lib_cut = 1000,
              group = "diet", struc_zero = TRUE, neg_lb = FALSE,
              tol = 1e-5, max_iter = 100, conserve = TRUE,
              alpha = 0.05, global = TRUE)

```
KR. Stan

**Comment by FrederickHuangLin** [comment]
Hi @stan-iakhno,

You caught a BUG! It turns out the ANCOMBC algirithm assumes that rownames are taxa names by default. The following codes should work:

```
otu_mat = as(otu_table(ps), "matrix")
meta = as(sample_data(ps), "data.frame")
tax_mat = as(tax_table(ps), "matrix")
OTU = otu_table(t(otu_mat), taxa_are_rows = TRUE)
META = sample_data(meta)
TAX = tax_table(tax_mat)
ps2 = phyloseq(OTU, META, TAX)
out = ancombc(phyloseq = ps2, formula = "diet",
              p_adj_method = "holm", zero_cut = 0.90, lib_cut = 1000,
              group = "diet", struc_zero = TRUE, neg_lb = FALSE,
              tol = 1e-5, max_iter = 100, conserve = TRUE,
              alpha = 0.05, global = TRUE)
```

Again, thanks for catching this and I will update the package accordingly.

Best,

Huang

**Comment by stan-iakhno** [comment]
Hi @FrederickHuangLin,

It is a pleasure! Thanks for a very nice piece of scientific work! 

Best. Stanislav
