### ISSUE TITLE
Confusion about results interpretion

### ISSUE THREAD

**Issue by JinjiPang** [FrederickHuangLin/ANCOMBC#72]
Hi Dr. Lin, 

I met some confusions when I tried to interpret the ANCOM-BC results.

First, I am trying to compare the DA(Differential Abundant) phyla between "Positive" group and "Negative" group, I believe the "Negative" group was used as the reference group here in my analysis.  According to the LFC( Log Fold Change) values, I want to conclude that phyla such as _Halobacterota_ and _Campilobacterota_ are more abundant in the "Positive" group, because their LFC values are positive. But when I checked their RA(relative abundance), I found the RA of _Campilobacterota_ was higher in the "Negative" group when compared with the "Positive" group. Similarly, the LFC value for _Bacteroidota_ is negative, which means it should be more abundant in the reference ("Negative") group, but the RA of _Bacteroidota_  was higher in the "Positive" group than the "Negative" group. I know I am not supposed to compare the RA values directly, but I just want to make sure that it is possible to see such scenarios.

![Screen Shot 2022-06-29 at 1 29 47 PM](https://user-images.githubusercontent.com/69986588/176510505-b33678f5-0a8b-476f-958a-c7c8074dcd0d.png)

Second, I am trying to compare the DA phyla between "Treatment" group and "Control" group,  I believe the "Control" group was used as the reference group here in my analysis. Here, I saw _Thermoplasmatota_ has a negative LFC value, which should lead to the conclusion that" _Thermoplasmatota_ is more abundant in the "Control" group". However, the RA of _Thermoplasmatota_  in the "Control" group is 0.00%. Is this also because of the structural zeros?

<img width="784" alt="Screen Shot 2022-06-29 at 1 28 06 PM" src="https://user-images.githubusercontent.com/69986588/176513277-36938d18-3770-4097-bf58-c5e19da357b2.png">

I hope I have described my questions clearly, if not, please feel free to let me know.

Best regards,
Jinji Pang

**Comment by FrederickHuangLin** [comment]
Hi @JinjiPang,

Please find below my responses to your questions.

>  I know I am not supposed to compare the RA values directly, but I just want to make sure that it is possible to see such scenarios.

You are right. Since ANCOM-BC is for absolute abundances, it is not surprising to see the change of directions if compared with relative abundances.

> Is this also because of the structural zeros?

Yes, as you can see, _Thermoplasmatota_ is another case of presence vs. absence, so the p and q-values are set to 0s automatically. However, I do realize the LFC value seems misleading here. Perhaps I should change it to `Inf` to remind people to check the `zero_ind` table. What do you think?

Best,
Huang

**Comment by JinjiPang** [comment]
Hi Dr.Lin@FrederickHuangLin,

Thank you for your reply. I think change it to `Inf` is a good strategy. Or maybe you can mention some special cases in the `vignettes` as examples. For me, this happened multiple times that I had a taxon with 0 abundance in one group but is presence in the other group; therefore, I got confused. But overall, I think your package is really helpful and well-explained by you papers and the `vignettes`.

I thought I have updated this `issue` to add my third question but apparently I have not. 
Third, I also wonder how to interpret the log fold change(LFC)? Is that means logarithm to base e? For example, if I have two groups, say A and B, where A is the reference group. One taxon(Z) has a significant LFC(B-A)=2, with that I know that group B has enriched absolute abundances of this taxon. But how can I interpret the quantitative abundance relationship here? Is that `LFC=2` means `log_e (B(absolute abundance of Z)/A(absolute abundance of Z))=2`?
I see Log2 fold change a lot in the previous studies, but I haven't seen LFC that frequent; thus I am wondering how to interpret the LFC values.

Sincerely,
Jinji

**Comment by FrederickHuangLin** [comment]
Thanks for your suggestion! I will think about what the best strategy is to show the LFC for structural zeros in the next update.

Meanwhile, as for the interpretation of LFC, yes, it is the natural log and what you wrote is correct.

Best,
Huang
