### ISSUE TITLE
Comparison of 4 groups

### ISSUE THREAD

**Issue by Anaherasm** [FrederickHuangLin/ANCOMBC#73]
Hello,

I am Ana, a Veterinary Student form Spain. I would like to compare the microbiome composition of sows given 4 different treatments, and see if there is any difference in the relative abundance. I performed ANCOMBC with global results, but I am not sure if that is the best way, nor how to know which of the 4 groups is the one having the significant differencial abundant data.

Thank you in advance for your help.
Ana

**Comment by andrebolerbarros** [comment]
This is an interesting question, because I would imagine you are interested in post-hoc, pairwise comparisons right? Well, either you subset pairs & perform the `ancombc` function or some post-hoc approach needs to be developed (like `emmeans` for example?). 

Honestly, the subsetting approach looks the pratical one in the short term but, I have some reservations regarding if it would be correct or not.

**Comment by Anaherasm** [comment]
Thank you your response. Exactly, that would be what I want to do. I performed the ANCOMBC analysis with global=T, since I understood that that would tell me wether there is any difference between 2 or more groups. But I wanted to know where were the differences exactly. I'll do what you propose, to perform the ANCOMBC between each pair (even though I am not sure if its the most correct one)

**Comment by andrebolerbarros** [comment]
Yeah, in statistical terms, it might not be the most correct one indeed. One solution would be to double-correct the p-values for comparisons (for example, holm for multiple comparison & FDR for multiple hypothesis testing) but, that also sounds like a tad overkill (although, if you get p-values with this approach, you might be on the safe side indeed). Another solution might be either use a stringent alpha criteria (let's say 0.01) or use a Fold Change threshold as filtering criteria as well (you might filter small changes that can be attributed to noise).

**Comment by FrederickHuangLin** [comment]
Thanks for your question, @Anaherasm, and thanks for your answer, @andrebolerbarros!

I agree with @andrebolerbarros that if you are interested in post-hoc, pairwise comparisons, you can perform ANCOMBC between each pair at this moment.

I understand it is not satisfying as it could inflate the FDR but double-correcting the p-values seems too conservative. We have the updated methodology ready and decided to implement a mixed-directional FDR (mdFDR) control for such pairwise comparison case. I am updating the package now and waiting for more unit testings. There is gonna be a major update for ANCOMBC package in a month or two to reflect this new feature (in addition to trend test and repeated measures).

Best,
Huang

**Comment by andrebolerbarros** [comment]
Thanks @FrederickHuangLin! And very good news indeed!

Considering you are performing major updates to the package, have you considered to organize the final results more in a user-friendly table, a similar table to the one DESeq2 (https://bioconductor.org/packages/release/bioc/html/DESeq2.html) produces, for example? It would summarize the results in a more consise fashion and would make the end-user life easier, that would not need to merge several tables.

If you prefer, I can open a suggestion/issue with this contribution.

Cheers,

André

**Comment by FrederickHuangLin** [comment]
That is a great idea @andrebolerbarros!

Feel free to open a suggestion/issue regarding it.

Best,
Huang

**Comment by Anaherasm** [comment]
Thank you to both of you for your kind answers. I will do as you say. However, I then have a doubt regarding the global option for analysis: i have thought that it means that, when you have more than one option, if its significant, it means that there is at least one difference between groups of comparions, even if it doesn't especify which groups are different. Am I correct, and then it would be useful for me, or I have understood it completely wrong???

**Comment by FrederickHuangLin** [comment]
Hi @Anaherasm,

> if its significant, it means that there is at least one difference between groups of comparions, even if it doesn't especify which groups are different

That is completely correct.

Best,
Huang

**Comment by Anaherasm** [comment]
Perfect, thank you for your answer

**Comment by kazubado33** [comment]
Thanks for the great discussion.

>  I am updating the package now and waiting for more unit testings. There is gonna be a major update for ANCOMBC package in a month or two to reflect this new feature (in addition to trend test and repeated measures).

Has there been a major update to incorporate a mixed-directional FDR (mdFDR) model yet at this time?

Thank you in advance for your help.
kazubado33

**Comment by FrederickHuangLin** [comment]
Hi @kazubado33,

I am pleased to share with you that the major update for `ANCOMBC` package has been completed. Here are some highlighted new features:

- Add `ancombc2` function, which supports pairwise test (with mdFDR control) and trend test for both cross-sectional and repeated measurements data
- Add sensitivity analysis for pseudo-count addition
- Fully support the `(Tree)SummarizedExperiment` class
- A more user-friendly output layout

I just pushed the changes to the Bioconductor branches. It might take a few business days for the package to become available (but the `devel` version is ready here!).

Best,
Huang

**Comment by marwa38** [comment]
Hi @FrederickHuangLin 
Many thanks for sharing the latest update, could you please let me know if this conda https://anaconda.org/bioconda/bioconductor-ancombc is supported and developed by you and had the recent features?
Thank you 
Marwa

**Comment by FrederickHuangLin** [comment]
Hi @marwa38,

I am not the developer or maintainer of the bioconda package, but it seems that it is up-to-date (v2.0.1).

Best,
Huang
