### ISSUE TITLE
User-friendly Result table

### ISSUE THREAD

**Issue by andrebolerbarros** [FrederickHuangLin/ANCOMBC#75]
As posted in Issue #73:

Considering you are performing major updates to the package, have you considered to organize the final results more in a user-friendly table, a similar table to the one DESeq2 (https://bioconductor.org/packages/release/bioc/html/DESeq2.html) produces, for example? It would summarize the results in a more consise fashion and would make the end-user life easier, that would not need to merge several tables.

Cheers,

André

**Comment by andrebolerbarros** [comment]
Right now, after performing the `ancombc` function and store it in an objected called `res1`, I organize the data like the following:

```
sum_res1<-data.frame(row.names = rownames(res1$res$beta),
                     LFC=res1$res$beta$comparison,  #getting the foldchange
                     se=res1$res$se$comparison, #getting the standard error of the estimate of foldchange,
                     W=res1$res$W$comparison, #getting the information regarding the W
                     padj=res1$res$q_val$comparison #getting the adjusted p-value
)
```
One could think you could add additional columns, like the `diff_abn` to the table, just to be sure (although, by leaving it out, one could "play" with more stringent or laxed alpha values withouth having to re-run the function).

**Comment by andrebolerbarros** [comment]
Another suggestion: you could add an option to the `ancombc` function if the user would like to merge the result table with the `tax_table` from the phyloseq object.

**Comment by FrederickHuangLin** [comment]
Hi @andrebolerbarros,

I am pleased to share with you that the major update for `ANCOMBC` package has been completed. Here are some highlighted new features:

- Add `ancombc2` function, which supports pairwise test and trend test for both cross-sectional and repeated measurements data
- Add sensitivity analysis for pseudo-count addition
- Fully support the `(Tree)SummarizedExperiment` class
- A more user-friendly output layout

I just pushed the changes to the Bioconductor branches. It might take a few business days for the package to become available (but the `devel` version is ready here!).

Best,
Huang

**Comment by andrebolerbarros** [comment]
Hi @FrederickHuangLin,

Great news! Will check the new version ASAP.

Thanks!

**Comment by MushroomToast** [comment]
Is there anyway to stop the results being merged with the tax_table? I preferred when the table was a ID string but cant find in the vignette how to stop this happening now.

e.g. I want '029c72cf8dcfea2c5796e9b8fb9de0b9' reported as TRUE or FALSE, not 'uncultured_organism'

**Comment by kazubado33** [comment]
Hi @MushroomToast !

If tax_level is set to NULL, it appears to come out as ID string!

Ex.)
ancombc2( ~~~, tax_level = NULL, ~~~)
