### ISSUE TITLE
Installation error due to glmnet

### ISSUE THREAD

**Issue by DeniRibicic** [FrederickHuangLin/ANCOMBC#78]
Dear developers,

I am having issues installing the package due to trouble with the `glment` dependency.
Namely, when installing `ancombc` it requires the latest version of `glmnet` (v4.1-4), and due to some specific reasons I am unable to install this one.

Is there a way to circumvent this requirement and intall `ancombc` with `glmnet` version v4.1-2?

Thanks for any suggestion

**Comment by FrederickHuangLin** [comment]
Hi @DeniRibicic,

What is the exact error message? It looks weird seems `ancombc` package has no dependencies on `glmnet`.

Best,
Huang
