### ISSUE TITLE
Understanding the Output

### ISSUE THREAD

**Issue by shrez28** [FrederickHuangLin/ANCOMBC#8]
Hi Frederick,

Thanks for developing the tool for compositional data. 
I am new to microbiome analysis and trying to understand the output result from ANCOM-BC

I was trying use the data to identify differentially abundant KOs from PICRUST2 output.

I have an abundance table for features as rows (KO dataset) with samples as columns. I have 3 treatment groups (treatA, treatB, treatC), with sample size of 10/group. I modified the it formula from the example for my dataset;

out = ancombc(phyloseq = physeq2, formula = "treatment", p_adj_method = "holm", zero_cut = 0.90, lib_cut = 1000, group = "treatment", struc_zero = TRUE, neg_lb = FALSE,  tol = 1e-5, max_iter = 100, conserve = TRUE,
alpha = 0.05, global = TRUE)

The output has two result files; res and res_global. I am trying to understand these files, and having a bit of trouble.
1. res_global = is the output for comparing the overall features that are differentially abundant between the three groups in my case. Can we think of the W statistic as analogous to the F statistic in one-way ANOVA? 
2. res = is the output for evaluating the pairwise comparisons for which I have attached a snapshot of the res$beta gives me file with three columns. beta being a coefficient based on which the W and SE are calculated.
a). Is the beta coefficient listed below the two columns treatB or treatC based comparison with treatA (treatB vs treatA; treatC vs treatA)?  but there is no comparison between treatB  vs treatC. Is this issue associated with the way I have setup the ancombc to run as mentioned above?
b). How do I interpret the first column the "Intercept"? I understand it is a result of applying linear regression to the differential abundance analysis.
c). How do I calculate the effect size for each feature?

[out1.txt](https://github.com/FrederickHuangLin/ANCOMBC/files/5452042/out1.txt)

If any of my questions are too basic, my apologies.  Any help is much appreciated.
Thank you.
Shrez

**Comment by FrederickHuangLin** [comment]
Hi Shrez,

Thanks for your interest in using ANCOMBC!

Please find the following my responses:

> res_global = is the output for comparing the overall features that are differentially abundant between the three groups in my case. Can we think of the W statistic as analogous to the F statistic in one-way ANOVA?

You are right! The global test is for testing whether there are some taxa that are differentially abundant in at least one group, in your case, treatment A, B, or C. Intuitively, the test statistic (W) is similar to F statistic in one-way ANOVA.

> Is the beta coefficient listed below the two columns treatB or treatC based comparison with treatA (treatB vs treatA; treatC vs treatA)? but there is no comparison between treatB vs treatC. Is this issue associated with the way I have setup the ancombc to run as mentioned above?

Yes! The first level (in your case, treatA) of a categorical value will be set as a reference level by default in R. You can check it by `levels(your group variable)`. So far there is no comparison other than those between the reference level. As you can see, if we aim to test for more comparisons, more price is needed for the issue of multiple comparisons. We are drafting the corresponding methodology, and the ANCOMBC package will be updated once the new paper gets published. (And rest assured, your code looks good!)

> How do I interpret the first column the "Intercept"? I understand it is a result of applying linear regression to the differential abundance analysis.

We realized that the "Intercept" column is not informative. We are considering removing it in our next release.

> How do I calculate the effect size for each feature?

The coefficients (`beta`) are "unstandardized effect sizes", and the `W` statistics are "standardized effect sizes" :)

Best,

Huang

**Comment by shrez28** [comment]
Thanks for the explanations, appreciate it. Will look out for the subsequent methods paper. 
1. Just to make sure I understand the effect size based on W statistic; high W statistic (with p/q value being significant) will indicate a large effect size for the corresponding feature. 
2. Then, would it be appropriate in interpreting that based on ANCOMBC we can identity the features that are differentially abundant and then compare the relative abundance of the selected features to understand the which group has increased/decreased.
Thanks once again for getting back,
Best,
Shrez

**Comment by FrederickHuangLin** [comment]
Hi Shrez,

Please find below my response to your questions:

> Just to make sure I understand the effect size based on W statistic; high W statistic (with p/q value being significant) will indicate a large effect size for the corresponding feature.

You are right!

> Can W be negative? I ask this because the W for the res_global output is always positive and values ranging from 0.049 to 174 whereas W from the res output file varies from -10.96 to +10.99. Is the W calculated differently for the global comparison than the pairwise? Is it that in res output the comparison indicates the direction of change with the -/+ sign?

Yes, the `W` statistics from the primary result (`res`), which aims to test for the effects of covariates of interest, can be either positive or negative and its sign indicates the direction; however, as you have realized, the `W` statistics from the global test (`res_global`) is always positive since it aims to test whether there exists at least one group that is significantly different from others, with no intention to tell the direction. We will add a new feature of telling the direction for multi-group comparisons in our next paper.

> Then, would it be appropriate in interpreting that based on ANCOMBC we can identify the features that are differentially abundant and then compare the relative abundance of the selected features to understand which group has increased/decreased.

It is not recommended to interpret the ANCOMBC results using relative abundances as it is developed specifically for testing (unobserved) absolute abundances in a unit volume of an ecosystem (for example, a tissue of the gut, which is not observable directly ). However, you can always visualize the results using relative abundances and see if changes in the relative abundance and absolute abundances are in the same way or not.

Best,
Huang

**Comment by shrez28** [comment]
Thanks for your explanation.

Best,
Shrez

**Comment by FrederickHuangLin** [comment]
Hi Shrez,

Sorry for responding late, please find below my responses:

> Is the W statistic from res out in log scale whereas the W statistic from res global is not in log scale?

Actually, the test statistics from both the primary analysis and global test are derived from the same log absolute abundances.

> Would a clr transformation on absolute abundance be a more appropriate tool for visualization than relative abundance?

I agree! Actually, the ANCOM plug-in in QIIME2 is using clr for visualizing the absolute abundance results. For more information, you can go to the last section of this [tutorial](https://docs.qiime2.org/2020.8/tutorials/moving-pictures/).

> Would it be possible to elaborate on the choice of the FDR correction method, the default method is Holm–Bonferroni compared to BH which is more commonly used in other DA methods. I read the explanation on page 10 of the paper, but couldn't quite understand it.

That is a great question! Indeed, the BH procedure is more commonly used for FDR control but it assumes that tests are independent or positively regression dependent, which may not be the case for microbiome data. Therefore, for a better FDR control, we turn to use a more conservative Holm–Bonferroni method which does not require any special correlation structure among tests. Although we have demonstrated in our paper (Supplementary Fig. 10) that using the BH procedure in ANCOMBC will not inflate FDR above the nominal level (5%), we let users determine which correction method is better for them based on their own study interests (more rigorous FDR control or more power).

Best,
Frederick

**Comment by shrez28** [comment]
Hi Frederick,
Thanks for you patience and explanations. Appreciate it.
Best,
Shrez
