### ISSUE TITLE
Prv_cut=0.1 still include taxa with prevalence below 10% in analysis?

### ISSUE THREAD

**Issue by Bigred-creator** [FrederickHuangLin/ANCOMBC#80]
Dear Huang,

In the R documentation for ANCOMBC prv_cut is defined as:

"a numerical fraction between 0 and 1. Taxa with prevalences less than prv_cut will be excluded in the analysis. Default is 0.10."

However, when I set  prv_cut=0.1 in my models I still get results where taxa that are found in lower abundance than 10% appear and with a calculated p and q value etc.

Have I misunderstood the term or am I doing something wrong?

Here is what I've done:

My model (where I want to analyze differential abundance at genus level between pigs (unit of study) affected by diarrhea (yes/no) adjusting for the random effect of them having different mothers):

set.seed(1)
out = ancom(phyloseq = genus_data,  p_adj_method = "holm",
             prv_cut = 0.1, lib_cut = 0, main_var = "Diarrhea_pw", 
             adj_formula = NULL, 
             rand_formula = "~ 1 | sow_no",
             lme_control = list(maxIter = 100, msMaxIter = 100, opt = "optim"), 
             struc_zero = TRUE, neg_lb = TRUE, alpha = 0.05, n_cl = 2)

**Diarrhea_pw:** my explanatory variable for grouping  (two levels: yes, no)
**sow_no:**  info on what mother the given piglet belong to

Picture of rand model res for one of the significant lowly abundant taxa:

![image](https://user-images.githubusercontent.com/100422240/178492710-077b96dd-87ca-4890-883b-caa06259f2e2.png)

Overall, this particular taxa as example had a mean relative abundance of 0.001 % amongst the other genera. And a mean relative abundance of 0.001% and 0.0008% in diarrhea groups "no" and "yes", respectively. 

Thanks for making ANCOMBC available!

Kind regards,
Martin

**Comment by eam12** [comment]
Unless I'm misunderstanding your question, I think the confusion is with the term "prevalence". I believe prv_cut is referring to the prevalence of a taxon across samples, not the abundance. So if a taxon is found (at any abundance) in fewer than 10% of samples, it will be excluded from analyses. The abundance of that taxon, assuming it's above 0, does not play a role here.

**Comment by Bigred-creator** [comment]
That makes sense, thanks for clearing that up for me!

**Comment by FrederickHuangLin** [comment]
I just wanna say what @eam12 said is absolutely correct :)

Cheers,
Huang
