### ISSUE TITLE
ancom function not found

### ISSUE THREAD

**Issue by SerenaGalie** [FrederickHuangLin/ANCOMBC#81]
Hi all,

I have just downloaded ancombc package but the ancom function is not working. I have updated the related package tidyverse but the issue is still present.

Please, someone could help me?

Many thanks!

Serena

**Comment by FrederickHuangLin** [comment]
Hi Serena,

Which version of `ANCOMBC` are you using? The `ancom` function is only available after version 1.6.1.

If the version number is not the issue, please share your code and the error message.

Thanks,
Huang

**Comment by SerenaGalie** [comment]
Many thanks Huang for your prompt answer! I have achieved downloading again the last version of ANCOMBC by using instead the github URL. Now ancom function is working!

Many thanks again.

Serena
