### ISSUE TITLE
raw data is TPM data for metagenomics?

### ISSUE THREAD

**Issue by Jigyasa3** [FrederickHuangLin/ANCOMBC#83]
Hi @FrederickHuangLin ,

Thanks for the great software! I am seen many references to using ANCOMBC on "raw data".  I am working with shotgun metagenomes where raw reads are affected by gene length, GC content, etc. among other things that require information not stored in the raw count table. So, I am generating TPM from raw counts (and doing stats on clr transformations of these TPMs)
I was wondering if I should use raw reads or TPM in ANCOMBC?

Looking forward to your reply!

**Comment by FrederickHuangLin** [comment]
Hi @Jigyasa3,

My apologies for getting back to you late!

You are right, `ANCOMBC` was originally developed for raw abundances generated from 16S rRNA sequencing, but it is not limited to the 16S data but is also applicable to other compositional data.

Back to your data, I think you should apply `ANCOMBC` to the raw counts as `ANCOMBC` has its own built-in normalization procedure. Using TPM would somehow "over-normalize" the data. I am aware that these raw counts might suffer more biases (in addition to sample-specific bias addressed in the current `ancombc` function); in our next iteration, the `ancombc2` function will take care of more sources of biases.

Best,
Huang
