### ISSUE TITLE
Error in `[.data.frame`(meta_data, , group) : undefined columns selected

### ISSUE THREAD

**Issue by mariamaseng** [FrederickHuangLin/ANCOMBC#84]
Hi!

I want to run ANCOMBC on my data which I have in phyloseq-format. However, I am running into a problem. 
I get the error "Error in `[.data.frame`(meta_data, , group) : undefined columns selected" - and suspect that it is due to not identifying the column for the formula, but I do see it there. 

Any idea about this?

My code: 
#Family level data
family_data = aggregate_taxa(p3, "Family")
#Run ancombc function
out = ancombc(phyloseq = family_data, formula = "sex", 
              p_adj_method = "holm", prv_cut = 0.10, lib_cut = 1000, 
              group = "region", struc_zero = TRUE, neg_lb = TRUE, tol = 1e-5, 
              max_iter = 100, conserve = TRUE, alpha = 0.05, global = TRUE)

_error: _Error in `[.data.frame`(meta_data, , group) : undefined columns selected__

However, if I do this: 
p3
summary(meta(p3)$sex)

it gives me this output: 

_phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 128 taxa and 1413 samples ]
sample_data() Sample Data:       [ 1413 samples by 84 sample variables ]
tax_table()   Taxonomy Table:    [ 128 taxa by 6 taxonomic ranks ]
 
  0   1 
683 654_

So my phyloseq and "sex" variable seems to be alright. 

Thanks for your help!

**Comment by FrederickHuangLin** [comment]
Hi @mariamaseng,

Please check whether your metadata contain `region` variable as you have specified `group = "region"`. If so, the formula should be `formula = "sex + region"` (the group variable should also be in the formula).

Best,
Huang

**Comment by mariamaseng** [comment]
Ah, thanks a lot! That was it.
