### ISSUE TITLE
"feature_table_pre_process" function not found

### ISSUE THREAD

**Issue by sunsvet** [FrederickHuangLin/ANCOMBC#86]
Hello,

I have just ran this code to install the package. 
```{r}
if (!requireNamespace("BiocManager", quietly=TRUE))
    install.packages("BiocManager")
BiocManager::install("ANCOMBC")
library("ANCOMBC")
```

After that I have run: 
```{r}
ancom_table <- feature_table_pre_process(taxa.table, metadata, sample.var="ID", group_var = "Group", out_cut = 0.05, zero_cut = 1, lib_cut = 1e6, neg_lb)

```
and I get an error: "could not find function "feature_table_pre_process". 

Any ideas what this might be the case?

**Comment by EcoJess94** [comment]
Did you manage to solve this? I am having the same issue!

**Comment by sunsvet** [comment]
Hi Jess,
I ended up following a tutorial where you transform the file into a phyloseq file and then run without the pre_process function as was suggested here: https://github.com/FrederickHuangLin/ANCOM-BC-Code-Archive/issues/10 
Good luck!

**Comment by FrederickHuangLin** [comment]
Hi @sunsvet and @EcoJess94,

The `feature_table_pre_process` function is for the `ancombc` standalone code and is no longer maintained. The `ANCOMBC` R package does not contain this function anymore. For details. you can check this [user manual](https://www.bioconductor.org/packages/release/bioc/manuals/ANCOMBC/man/ANCOMBC.pdf)

Best,
Huang
