### ISSUE TITLE
[Feature request] Generalize ANCOM-BC to work on all compositional data and not just Phyloseq objects

### ISSUE THREAD

**Issue by jolespin** [FrederickHuangLin/ANCOMBC#89]
I'd like to use this on gene expression data but noticed that there is a strict dependency on phyloesq objects. Is there a way to just give it a counts table? Maybe with some low level function that's used in the backend?

**Comment by FrederickHuangLin** [comment]
Thank you for your recommendation, @jolespin! I am modifying the devel version of `ancombc` now. Will incorporate the feature you requested.

Best,
Huang

**Comment by jolespin** [comment]
Thank you! This would be GREATLY appreciated. I am going to try to use this as the starting point for all of my CoDA (including non-microbiome research).

**Comment by FrederickHuangLin** [comment]
Hi @jolespin,

I am pleased to share with you that the major update for `ANCOMBC` package has been completed. Here are some highlighted new features:

- Add `ancombc2` function, which supports pairwise test and trend test for both cross-sectional and repeated measurements data
- Add sensitivity analysis for pseudo-count addition
- Fully support the `SummarizedExperiment`, `TreeSummarizedExperimen`, and `phyloseq` classes
- A more user-friendly output layout

A count table can be easily transformed into a `(Tree)SummarizedExperimen` or `phyloseq` object. For instance, you can see this [tutorial](https://microbiome.github.io/OMA/containers.html#loading-experimental-microbiome-data).

I just pushed the changes to the Bioconductor branches. It might take a few business days for the package to become available (but the `devel` version is ready here!).

Best,
Huang
