### ISSUE TITLE
z-transformed covariates

### ISSUE THREAD

**Issue by SimoneAnza** [FrederickHuangLin/ANCOMBC#9]
Hi Frederick,

thank you for developing such amazing tool! I am using it for my studies on gut microbiome and stress and I was wondering if I could z-transform my covariate (stress) before runing ancombc() to better interpret the results. 

Do you think it could work? my code is:

out = ancombc(phyloseq = phylum_data, formula = "stress + season + sex + age_cat",  p_adj_method = "holm",
              zero_cut = 0.90, lib_cut = 1000,  group = NULL,  struc_zero = FALSE,  neg_lb = FALSE, tol = 1e-5, max_iter = 100,
              conserve = TRUE, alpha = 0.05,  global = FALSE)

but before of it, i guess I should z-transform the covariate in the data summary part or even before? should i do it before and then run the following?

summary_template =
  list("stress" =
         list("min" = ~ min(.data$stress, na.rm = TRUE),
              "max" = ~ max(.data$stress, na.rm = TRUE),
              "mean (sd)" = ~ mean_sd(.data$stress, na_rm = TRUE, 
                                      show_n = "never")),
       "sex" =
         list("F" = ~ n_perc0(.data$sex == "female", na_rm = TRUE),
              "M" = ~ n_perc0(.data$sex == "male", na_rm = TRUE),
              "NA" = ~ n_perc0(is.na(.data$sex))), and so on...

Thank you!

Cheers,

Simone

**Comment by FrederickHuangLin** [comment]
Hi Simone,

Thanks for your interest in ANCOMBC!

From a statistical perspective, z-transform (if I understand it correctly, usually z-transform means standardization in statistics) helps reduce collinearity (a little bit) in linear regressions for continuous variables. For more information, see [here](https://stats.stackexchange.com/questions/16710/does-standardising-independent-variables-reduce-collinearity).

However, I believe whether it is easier to interpret the results more depends on the scientific point of view (the same as the data summary part).

Hope it helps :)

Frederick

**Comment by simone-anza** [comment]
What I mean was if I can center and scale a variable (z-transformation) with mean = 0 and SD = 1. This procedure helps to understand the estimates of linear models without affecting their estimate values. I noticed that it produces different results if I z-transform the covariate or not before running ANCOM-BC
