### ISSUE TITLE
could not find function "datatable"

### ISSUE THREAD

**Issue by jorondo1** [FrederickHuangLin/ANCOMBC#90]
Hi, I am trying ANCOM-BC for the first time, following [this tutorial](https://www.bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC.html#run-ancombc-function). 

When running the functions in 4.1 I am getting the following error:

`Error in datatable(., caption = "Differentially Abundant Taxa from the Primary Result") : 
  could not find function "datatable"
`
Is there a dependency that could be missing?

**Comment by FrederickHuangLin** [comment]
Hi @jorondo1,

The `datatable` function is from [DT](https://rstudio.github.io/DT/) R package.

Best,
Huang

**Comment by jorondo1** [comment]
Thanks !
