### ISSUE TITLE
Error in matrix(value, nrow = nr, dimnames = list(rn, cn)) :    length of 'dimnames' [2] not equal to array extent

### ISSUE THREAD

**Issue by PeterCroninX** [FrederickHuangLin/ANCOMBC#92]
Hi there,

I keep encountering the error in the title:

**Error in matrix(value, nrow = nr, dimnames = list(rn, cn)) :    length of 'dimnames' [2] not equal to array extent**

My code is as follows:
OTU = otu_table(OTU_Table,taxa_are_rows = TRUE)
META = sample_data(Meta)

physeq = phyloseq(OTU, META)

######## Do the ANCOMBC #########
out <- ancombc(phyloseq = physeq, formula = "Gender + Age + BMI + Group", 
               p_adj_method = "fdr", zero_cut = 0.9, lib_cut = 1, 
               group = "Group", struc_zero = TRUE, neg_lb = TRUE, tol = 1e-5, 
               max_iter = 100, conserve = FALSE, alpha = 0.05, global = TRUE)

Not really sure what to do. Help greatly appreciated.

Kind regards,

P

**Comment by FrederickHuangLin** [comment]
Hi @PeterCx, 

Which version of `ANCOMBC` are you using? Since version 1.6.x, the `zero_cut` argument is no longer supported.

Best,
Huang

**Comment by linxy29** [comment]
Hi @FrederickHuangLin ,

I also come across the same error. The code I used is:

`set.seed(123)
otu_mat = matrix(sample(1:100, 100, replace = TRUE), nrow = 10, ncol = 10)
rownames(otu_mat) = paste0("taxon", 1:nrow(otu_mat))
colnames(otu_mat) = paste0("sample", 1:ncol(otu_mat))


meta = data.frame(group = sample(LETTERS[1:3], size = 10, replace = TRUE) %>% as.factor(),
                  row.names = paste0("sample", 1:ncol(otu_mat)),
                  stringsAsFactors = FALSE)

tax_mat = matrix(sample(letters, 70, replace = TRUE),
                 nrow = nrow(otu_mat), ncol = 7)
rownames(tax_mat) = rownames(otu_mat)
colnames(tax_mat) = c("Kingdom", "Phylum", "Class", "Order",
                      "Family", "Genus", "Species")

OTU = otu_table(otu_mat, taxa_are_rows = TRUE)
META = sample_data(meta)
TAX = tax_table(tax_mat)
physeq = phyloseq(OTU, META, TAX)

out = ancombc(phyloseq = physeq, formula = "group",
              p_adj_method = "holm", zero_cut = 0.90, lib_cut = 1000,
              group = "group", struc_zero = TRUE, neg_lb = FALSE,
              tol = 1e-5, max_iter = 100, conserve = TRUE,
              alpha = 0.05, global = TRUE)`

The version I used is: 
`ANCOMBC              * 1.2.2      2021-08-15 [1] Bioconductor`

**Comment by linxy29** [comment]
I followed the installation instruction in this website: https://bioconductor.org/packages/devel/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC.html. I installed the `ANCOMBC * 1.2.2 2021-08-15 [1] Bioconductor` version, but not the `ANCOMBC_2.1.1` shown in this tutorial. Any idea why?

**Comment by FrederickHuangLin** [comment]
Hi @linxy29,

`ANCOMBC` 2.0.x is available in Bioconductor 3.16. Please make sure you have updated your Bioconductor as well.

Best,
Huang
