### ISSUE TITLE
Is the ANCOMBC similarly designed to assume that few features will change between groups?

### ISSUE THREAD

**Issue by kazubado33** [FrederickHuangLin/ANCOMBC#94]
Hello, everyone.
Thanks for developing such a great Tool.

I learned about ANCOM from Qiime's analysis.

In Qiime's Tutorial, they mention the following: 
> ANCOM assumes that few (less than about 25%) of the features are changing between groups. If you expect that more features are changing between your groups, you should not use ANCOM as it will be more error-prone (an increase in both Type I and Type II errors is possible). 

Is ANCOMBC similarly assumed for cases where there is little difference in characteristics between groups?
Should ANCOMBC not be used if there is significant variation among groups?

Thanks, 
kazubado33

**Comment by FrederickHuangLin** [comment]
Hi @kazubado33,

This is a great question.

ANCOM-BC methodology does the bias correction by fitting a Gaussian mixture model, which assumes there are **some** taxa changing between covariates of interest, while **some** taxa remain unchanged. As for the effect sizes of each covariate, it means some effect sizes are positive, some are negative, and some are zeros; thus, these effect sizes form a "Gaussian" mixture.

If you believe every taxon will change during a strong abruption of the environment (e.g., antibiotics usage), then the ANCOM-BC assumption might not hold.

Best,
Huang

**Comment by kazubado33** [comment]
Hello Huang!

Sorry for the very late reply.
Thank you for your excellent response.

Thanks,
kazubado33
